### PR TITLE
Fix regression in Travis file on commit db3bea25

### PR DESCRIPTION
**Pull request by ekrich**
@LeeTibbert Thanks for finding this problem.

### CODE REVIEW

**Comment by ekrich** [comment]
@sjrd If this could be merged once it clears CI that would be great. We weren't running the correct tests in CI.

**Comment by sjrd** [comment]
What's the difference between `MODE` and `TEST_COMMAND`?

**Comment by ekrich** [comment]
The `MODE` is used before in the `script` portion of the Travis file to control what gets run but then the `TEST_COMMAND` gets past to the Docker - that is a bit confusing to have both the `sbt` alias `test-runtime` and the switch string for the Travis `script` to be the same.

**Comment by ekrich** [comment]
Thanks for the quick turn around.

**Pull request merged**
