### PR TITLE
WIP of posix regexes using regex.h for the ScalaXhack event

### PR DESCRIPTION
**Pull request by rberenguel**
Just so it gets pushed somewhere :)

### CODE REVIEW

**Comment by rberenguel** [comment]
CLA signed by now, but this is still a WIP that does not even need a review yet :)

**Comment by densh** [comment]
Hi @rberenguel, thanks for contribution! Looking forward to this becoming non-WIP and merged!

**Comment by densh** [comment]
Next step is to run `bin/scalafmt` every once in a while. Otherwise, CI fails.

**Comment by densh** [comment]
Needs a rebase & reformat due to scalafmt upgrade.

**Comment by densh** [comment]
@rberenguel Thanks for looking at the issue!

History for this one seems to be complicately broken. The diff is gigantic and includes unrelated changes. Feel free to re-open with a cherry-picked/squashed version of the relavant changes in a new PR. As a rule of thumb, avoid merges and do rebase instead to get up-to-date with latest master.

**Comment by rberenguel** [comment]
@densh yup, sorry, when I started I wasn't really sure where and how and created too many commits with too little meat in them. Now I'll probably restart it from almost scratch to get it cleaner in one (hopefully) go. 

Oh, and maybe at [the docs](http://scala-native.readthedocs.io/en/latest/contrib/contributing.html) we should state favoured rebase from master. At work it's the exact opposite!

**Comment by densh** [comment]
You're right we should mention this in the docs! It's very much a question of convention, we used to have merge-based workflow originally but it got really hard to track all of the WIP branches of different people so we switched to rebase-centric approach instead.

**Comment by krzkaczor** [comment]
@rberenguel @densh waiting for regex to be implemented :) Let me know if I can help you anyhow.

**Comment by rberenguel** [comment]
@krzkaczor thanks for the encouragement! I need less stuff to do at work :D I'm at it right now, let's see if I can wrap it today

**Pull request closed without merging**
