### PR TITLE
sudo chmod +x bin/travis_setup.sh

### PR DESCRIPTION
**Pull request by muxanick**
Fix for Travis on fresh CI

### CODE REVIEW

**Comment by muxanick** [comment]
I think CI fail is unrelated to this change

**Comment by densh** [comment]
@muxanick Is this change even necessary? I have an impression that it works fine now without it.

**Comment by muxanick** [comment]
@densh See this: https://travis-ci.org/scala-native/scala-native/jobs/236199137

**Comment by densh** [comment]
@muxanick How about we do `bash bin/travis_setup.sh` instead? Changing file permissions in CI doesn't feel right.

**Comment by muxanick** [comment]
@densh We do that for sbt: https://github.com/scala-native/scala-native/search?utf8=%E2%9C%93&q=sudo+chmod&type=
do we want to change that as well?

**Comment by densh** [comment]
That's true, `sbt` script regressed recently. Whatever we do, we should do it in the same way for both.

**Pull request merged**
