### PR TITLE
java.nio.* port form Scala.js

### PR DESCRIPTION
**Pull request by siriux**
Only some classes implemented. Base functionality in buffers is working. Charsets fail.

### CODE REVIEW

**Comment by siriux** [comment]
The buffers (byte and char) seem to be working in simple tests like this:

```
    import java.nio._

    val ba = new Array[Byte](100)
    val bb = ByteBuffer.wrap(ba, 0, 100)

    bb.put(10, 1.toByte)
    val n = bb.get(10)
    fprintf(stdout, c"Number %d\n", n)
```

On the other hand, if I try to use Charset in this example (first steps to convert string to cstring):

```
    val s = "A java string"
    val ca = s.toCharArray()
    val cb = CharBuffer.wrap(ca, 0, s.length())
    val buffer = Charset.defaultCharset().encode(cb)
```

It crashes with 

`[error] (*:nativeLink) java.util.NoSuchElementException: key not found: Local(src,16)`

If I remove `.encode(cb)` it doesn't crash, so the problem is there.

**Comment by densh** [comment]
@siriux You've discovered a compiler bug. I'm currently working on a fix.

**Comment by densh** [comment]
I've just fixed it in https://github.com/scala-native/scala-native/pull/187. Now it fails at runtime due to missing implementation of array copy, but that's coming soon in https://github.com/scala-native/scala-native/pull/184.

**Comment by densh** [comment]
The two block issues has been fixed, please rebase on top of latest master.

**Comment by siriux** [comment]
Done. But I still get an error.

When trying to get the default charset `Charset.defaultCharset()` I get this error `terminate called after throwing an instance of 'scalanative::ExceptionWrapper*'`.

**Comment by densh** [comment]
We currently don't print stack trace on exception crashing the app. You can see it if you ran the app from lldb. (i.e. do `> lldb sandbox-out` and then `run` and then `bt` in the lldb shell.)

**Comment by siriux** [comment]
Thanks, that was helpful. I'm hitting an unimplemented method that I thought it was not used.

**Comment by siriux** [comment]
I thought that the problem was in my unimplemented function, but is not. Does this error tell you something? The implementation of newArray in ScalaTag seems fine.

```
    ...
    frame #7: 0x000000000040f6dc hello-out`scala.Predef$::???_nothing + 44
    frame #8: 0x000000000044ee72 hello-out`scala.reflect.ClassTag$class$::newArray_trait.scala.reflect.ClassTag_i32_class.java.lang.Object + 1090
```

**Comment by densh** [comment]
Use of java reflection is pervasive. I'll see what can be done for this particular method. Shouldn't be too big of a problem to implement it differently.

**Comment by densh** [comment]
This pr is actually good to go, given that the failure is unrelated to nio. I'd file it as a separate issue. Squash in one commit and it's LGTM.

**Comment by siriux** [comment]
Done

**Comment by densh** [comment]
LGTM, thanks for the contribution!

**Pull request merged**
