### PR TITLE
+javalib Add CompletionException to javalib.

### PR DESCRIPTION
**Pull request by He-Pin**
refs: https://github.com/scala-native/scala-native/issues/3165

### CODE REVIEW

**Comment by LeeTibbert** [comment]
@He-Pin 

Good to see progress on Issue #3165.  It keeps slipping further & further down my "I hope to 
work on that someday" guilt/dream list.


There are build errors in the multiarch part of CI.  I suggest that you ignore them as
unrelated to the content of this PR (I checked!).

I am chasing what changed in the CI environment sometime about Sept 7, 2023.
It appears to be a change outside of the SN repository.  

If you are interested in details, see or track PR #3481, where I am thrashing, or PR# 3478 where
I am tracking the problem.

Let me know if you have questions.

**Comment by He-Pin** [comment]
> @He-Pin 
> 
> Good to see progress on Issue #3165.  It keeps slipping further & further down my "I hope to 
> work on that someday" guilt/dream list.
> 
> 
> There are build errors in the multiarch part of CI.  I suggest that you ignore them as
> unrelated to the content of this PR (I checked!).
> 
> I am chasing what changed in the CI environment sometime about Sept 7, 2023.
> It appears to be a change outside of the SN repository.  
> 
> If you are interested in details, see or track PR #3481, where I am thrashing, or PR# 3478 where
> I am tracking the problem.
> 
> Let me know if you have questions.

Update the scalafmt version？new version has a native image, faster to fit

I want to port some classes that pekko/akka is using, but my notebook is pretty slow.

**Comment by LeeTibbert** [comment]
> Update the scalafmt version？new version has a native image, faster to fit

By 'native image' do you mean GraalVM or have they gotten Scala Native to work once again.
scalafmt on Scala Native was wicked fast but never shipped.

re: changing the scalafmt version used in the SN build.

@ekrich has done this several times, expending much effort and earning much merit.

@armanbilge seems to have scalafmt updates done automatically in several of their projects.
I see that in my stream of  GitHub notifications.

I think the major impediment is the amount of breakage and churn that gets introduced. 
I suspect, but have not tried, but from having kept a keen interest in Eric's prior efforts,
updating seems to be potentially more than changing a version number (I think that 
change is well contained).    

Proof would be to do a trial build using the current scalafmt version and see how many
files and what in them changes.  

We are going to have to update someday. Then again, I think we still support Clang 6.0.

**Comment by He-Pin** [comment]
Native image of scalafmt, I am using scala-cli fmt to format, but there us no native image for 3.6.1. I will try to submit a pr tomorrow with git blame ignored。

Networking is slow in China because of thr gfw, a pain in ass to continue open-source 😒

**Comment by He-Pin** [comment]
@LeeTibbert and you can take a look at pekko or akka project, I think with is more new contributor firendly 😃

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
