### PR TITLE
reformat NirGenExpr by scalafmt

### PR DESCRIPTION
**Pull request by catap**
The main reason to do it to support issue inside scalafmt: https://github.com/scalameta/scalafmt/issues/2299

### CODE REVIEW

**Review by sjrd — APPROVED** [review]

**Comment by sjrd** [comment]
@WojciechMazur Does the CI actually work for scalafmt? It ends with
```
error: UnexpectedError=8
```
but doesn't fail the build.

**Comment by ekrich** [comment]
I would think not. I took a stab at updating a while back and it is very difficult if not impossible to update without introducing lots of formatting changes even after changing `scalafmt` settings.

I do have some of the ideas to reduce whitespace changes but they too would also require some initial reformatting.

I could revive my PR for discussion.

**Comment by catap** [comment]
@ekrich I've updated only `scalafmt` version, and not settings. It was blind shot to support issue that I've opened at `scalafmt`.

@sjrd I feel that it doesn't work "very well" because `scalafmt` fails on `NirGenExpr.scala`.

**Comment by ekrich** [comment]
Please try and run the following to see if any file format changes would occur:
`scripts/scalafmt --test`

**Comment by catap** [comment]
@ekrich as expected.

` ./scripts/scalafmt` returns `0` and doesn't change anything.

```
? scala-native % ./scripts/scalafmt --test                                                                                          (git)-[NIR-scalafmt]
org.scalafmt.cli.FailedToFormat: /Users/catap/src/scala-native/nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenExpr.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded around line 1711
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:186)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:202)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:202)
earch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)nformatted files...
   32.6%at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:202)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:202)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:202)
	at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:251)
	at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:252)
	at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:294)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:72)
	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:48)
	at org.scalafmt.Scalafmt.format(Scalafmt.scala)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scalafmt.dynamic.ScalafmtReflect.format(ScalafmtReflect.scala:107)
	at org.scalafmt.dynamic.ScalafmtReflectConfig.format(ScalafmtReflectConfig.scala:121)
	at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$tryFormat$1(ScalafmtDynamic.scala:203)
	at scala.util.Try$.apply(Try.scala:213)
	at org.scalafmt.dynamic.ScalafmtDynamic.org$scalafmt$dynamic$ScalafmtDynamic$$tryFormat(ScalafmtDynamic.scala:188)
	at org.scalafmt.dynamic.ScalafmtDynamic$MySession.format(ScalafmtDynamic.scala:245)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:114)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4(ScalafmtDynamicRunner.scala:62)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4$adapted(ScalafmtDynamicRunner.scala:60)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
error: UnexpectedError=8
√ scala-native % echo $?                                                                                                            (git)-[NIR-scalafmt]
0
√ scala-native % git id                                                                                                             (git)-[NIR-scalafmt]
0409b4381%                                                                                                                                               √ scala-native % git status                                                                                                         (git)-[NIR-scalafmt]
On branch NIR-scalafmt
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
√ scala-native %  
```

**Comment by ekrich** [comment]
I think this is because `scalafmt` is using the version in the `.scalafmt.conf` file. The exploding search state has been fixed in a later version (by adding a setting) but is not a big issue except for that file and the fact that it is ugly.

**Comment by catap** [comment]
@ekrich you defently right. Thanks!

**Comment by catap** [comment]
@sjrd I've changed this PR to keep old version by adjust parameter to reformat `NirGenExpr.scala`.

And as nice bonus I've also changed behaviour of `./scripts/scalafmt` to return non zero exit code when it fails.

**Pull request merged**
