### PR TITLE
Implement java.util.Properties.list

### PR DESCRIPTION
**Pull request by sadhen**
## Changes
1. Impl `ju.Properties.list`
2. Add null check on `ju.Hashtable.put`

for the put method of Hashtable: 

> This class implements a hash table, which maps keys to values. Any non-null object can be used as a key or as a value. 

## Ref
+ #1064 
+ https://docs.oracle.com/javase/8/docs/api/java/util/Hashtable.html

### CODE REVIEW

**Comment by ekrich** [comment]
@sadhen Here is the previous PR I was speaking about. https://github.com/scala-native/scala-native/pull/1100

**Comment by ekrich** [comment]
Cool, this links the 2 together for other readers.

**Comment by sadhen** [comment]
@densh Please re-review.

**Comment by densh** [comment]
LGTM, thanks @sadhen! 👍

**Pull request merged**
