### PR TITLE
WIP: Fix 1664: Zero copy in posixlib time implementation

### PR DESCRIPTION
**Pull request by LeeTibbert**
We re-work the declaration and implementation of posixlib time to use
reasonable & checked pre-conditions to eliminate both the need to
copy structures and a layer of glue code.

This approach provides code simplification and a runtime performance boost
It originated as an attempt to correct, and does indeed correct, three flaws:
  1) a 0.4.0 regression in POSIX strftime where	it could read beyond
     the end of	allocated memory.

  2) a flaw in strptime where it could write beyond the end allocated memory.

  3) a flaw where localtime was not calling tzset() as required by
     POSIX and described in linux man pages.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
@ekrich, @catap can I solicit your thoughts and review of this PR? I understand if you have few or no cycles to devote
to it.  This work is the current state of discussions & WIP PRs the three of us have worked on over the past several
months.  I think you will see that I have built upon elements of your proposals and review of prior work.

There are going to be some systems where the approach does not work.
I believe those will not be many and can be addressed in detail as they
become known.  For the vast majority of users/systems the code should be both 
correct and much faster.

@ekrich Does this work on Apple?

@catap can you break this with your memory test harness?

The approach of this PR is limited to time.scala shows promise
for use in other places in posixlib & clib.

Of course, I welcome review, comment, and improvements from all people with an interest.

**Review by ekrich — COMMENTED** [review]
@LeeTibbert This does indeed work on `macOS`. I checked `sandbox` and `TimeTest`. I don't see anything jumping out at me and you have a pretty good pre-compiler check so any problems should not make it to runtime.

**Review by catap — APPROVED** [review]
I really like it

**Comment by LeeTibbert** [comment]
@catap @ekrich  Thank you for reviewing this. It gives me the confidence to advance it.

I know that it is not a thing in SN, as it is in the linux-kernel world, but I feel I should
add a `co-authored-by`  for each of you as the three of us have worked on this over
many a PR.  The final result is collaborative, not mine.  Well, the blunders are mine, I have
to fess up to those.

Please advise.

**Comment by sjrd** [comment]
Sorry for the very late reply here.

I am not a fan of the solution proposed here. It seems to me that it brings even more uncertainty wrt. its correctness than there was before. In fact, so far I don't understand what was wrong with the previous approach.

The approach proposed here is extremely sensitive to unspecified concerns. There are static tests that the C structs is not larger than the Scala definition, but that is not enough. The converse must also be true to be completely correct; indeed if we were to receive such a struct from C and then pass it by value somewhere, a full copy would be made, which would access unallocated memory as well. If some C implementations are going to give different sizes to this struct, I think we have no choice but to go through a copy from a Scala-known struct to the underlying C struct, and back. Anything else is a shot in the dark wrt. memory safety.

**Comment by ekrich** [comment]
@sjrd Do you think it would be possible that we actually create the platform structure and that the runtime only accesses the fields? This way the Scala Native defined struct can be a portable subset of fields that can be checked at link time - no accessing by field number. In this scenario the Scala Native struct definition is just like a facade or something?

**Comment by sjrd** [comment]
That doesn't seem possible with the current architecture of the NIR. When we compile to NIR, we already need to know the size of structs and the offsets or their fields.

**Comment by LeeTibbert** [comment]
superseded by PR #2160.

I intend to close this PR once I have created an Issue to discuss the zero-copy concept.
I think that is worthwhile and nigh on to essential for respectable performance 
but I do not want it to prevent solving an ugly, customer visible issue.

**Comment by LeeTibbert** [comment]
Closing. As promised, closing thoughts on the benefits & next steps for zero copy
structs are in Issue #2195.

I should note for anyone in the future reading this PR, that since it was submitted,
I have figured out a way to do zero copy "fast" path where the underlying 
libc allows, and the current "slow" path to cover all the cases .

**Pull request closed without merging**
