### PR TITLE
Prepare for release 0.4.10

### PR DESCRIPTION
**Pull request by WojciechMazur**
- Cherry-pick of backward compatible changes from main branch
- Set version to 0.4.10
- Update MiMa config
- Prepare changelog

### CODE REVIEW

**Comment by armanbilge** [comment]
Why is https://github.com/scala-native/scala-native/pull/3111/commits/a41c6f01e6314a99a6a384c5fe51f982a2c2c4e8 reverted, I guess it did not backport cleanly? cc @LeeTibbert

It's probably not worth the effort since 0.5.0 is on the horizon, but I was looking forward to that one 😅

**Comment by WojciechMazur** [comment]
> Why is [a41c6f0](https://github.com/scala-native/scala-native/commit/a41c6f01e6314a99a6a384c5fe51f982a2c2c4e8) reverted, I guess it did not backport cleanly?

That's exactly the case, there seemed to be something missing, because even if it compiled the tests were failing

**Comment by dongnguyenvt** [comment]
please help to revert https://github.com/scala-native/scala-native/pull/3111/commits/f95f6f62ec3aabc4c0802b10141615a91fb732f7 or update the [doc](https://github.com/scala-native/scala-native/pull/3111/commits/f95f6f62ec3aabc4c0802b10141615a91fb732f7#diff-21da6c72e7d6eef5f57246a55a1b9db80cadcca1ada96d851929311c5b513eaeR198) since I've unintentionally mention it should be released in 0.5.0

**Comment by WojciechMazur** [comment]
> please help to revert [f95f6f6](https://github.com/scala-native/scala-native/commit/f95f6f62ec3aabc4c0802b10141615a91fb732f7) or update the [doc](https://github.com/scala-native/scala-native/pull/3111/commits/f95f6f62ec3aabc4c0802b10141615a91fb732f7#diff-21da6c72e7d6eef5f57246a55a1b9db80cadcca1ada96d851929311c5b513eaeR198) since I've unintentionally mentioned it should be released in 0.5.0

Thank you for catching that, I've fixed the docs

**Comment by LeeTibbert** [comment]
| Why is [a41c6f0](https://github.com/scala-native/scala-native/commit/a41c6f01e6314a99a6a384c5fe51f982a2c2c4e8) reverted, I guess it did not backport cleanly?

Sorry that backporting this cost time.  After the 4.10 train leaves the station, I will take a run at backporting to 4.10
and see what the errors are.    

Some of the network related tests like to succeed on even days of the month only while others like odd days only.

**Comment by LeeTibbert** [comment]
| Revert "javalib UnixProcess now uses kevent FreeBSD64

Thank you for attempting to backport this fix.

Just FYI. From looking at the revert log, it seems like the problem here is that an intermediate PR to make
 UnixProcess use poll/kevent was not applied. That is sequence A->B->C appears to be missing step B.

Not worth futzing with 10 seconds before (or after) the 4.10 train is leaving. Just have to remember that
ProcessMonitor lives on in Unix & macOS in 4.10. Such is life.

**Pull request merged**
