### PR TITLE
Missing set methods

### LINKED ISSUE #3998: Javalib `Set.scala` is missing a number of methods.
This may read like a whine, but it is really a "forget-me-not".

Whilst working on what is now PR #3997, I became aware, like a freight car hitting you,
that javalib `Set.scala` is missing a number of methods.  The methods are there, but
commented out by a `Todo`.

IIRc, `equals` and `hashcode` are among the commented-out methods.  That can
never be a good sign.

It is true that, to my knowledge, no one has complained here about those missing
declarations in the eight or so years this has been true. It would be nice to get
ahead of the curve and not wait for complaints.

### PR DESCRIPTION
**Pull request by kyouko-taiga**
Fixes #3998.

### CODE REVIEW

**Comment by kyouko-taiga** [comment]
Re-check my CLA.

**Comment by ekrich** [comment]
@kyouko-taiga I think these methods are an artifact of when Scala Native had a problem in the compiler and `Set` and other interfaces did not inherit properly from `Collection` in this case. I noticed this because normally we try and stay in sync with Scala.js - https://github.com/scala-js/scala-js/blob/main/javalib/src/main/scala/java/util/Set.scala. I then referred to the JavaDoc - https://docs.oracle.com/javase/8/docs/api/java/util/Set.html - It seems that all of these methods are inherited from collection.

We have been meaning to sync up our collections somewhat with Scala.js as they have better tests and in general their compiler is more mature. 

I reviewed the JavaDoc and indeed the Scala.js is correct with exception of the `object Set` methods which should be here. If `Collection` or its super interface `Iterator` are missing methods then they should be put in those areas respectively. Either way this is a great effort to mathod our `javalib` more correct.

**Review by WojciechMazur — APPROVED** [review]

**Comment by ekrich** [comment]
@WojciechMazur is my comment above not applicable? In Scala.js the interface is empty because all the methods are defined in the Collection interface. At one time we needed to redefine methods in sub interfaces but that shouldn't be the case anymore?

**Comment by WojciechMazur** [comment]
I'm not sure which approach is better, but current implementation does mirror what Java does based on the Apache Harmony source code https://github.com/apache/harmony/blob/trunk/classlib/modules/luni/src/main/java/java/util/Set.java 
The methods are in fact duplicated but that's exactly what Java does.Also the mentioned Javadoc API page does confirm that - the only methods inherited from Collection are 
>
>Methods inherited from interface >java.util.Collection
>parallelStream, removeIf, stream
```
On the other hand later in the method details we can that these are specified in Collection,eg.

>Specified by:
>size in interface Collection<E>o

From our perspective each of the approaches seems to work fine. Maybe duplication was introduced as an mistake in early Java version and was kept for some reason, maybe there was real problem that it solve.

**Comment by ekrich** [comment]
Ok, I hadn't looked at any other implementation other than Scala.js and the docs and knew in the past Scala Native needed them repeated as otherwise it didn't work.

**Pull request merged**
