### PR TITLE
nativelib.regex improvements: have regex use JVM Character UC 6.3+warts

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This PR was motivated by Issue #78 in the [re2j](https://github.com/google/re2j) GitHub 
    repository:  "Replace CASE_RANGES with Character.to{Lower,Upper}Case()".

    This PR is also related to Issue #1542 "Unicode tables should be
    unified for consistency & minimal binary size" in this repository."
    It is a step on the road to fixing Issue $1542, not a complete fix.

    The intent is to reduce binary size and cognitive load by removing data
    tables and the code which used them. Java Character methods are used
    instead.

  * This PR makes the character set used by native.regex correspond,
    bug for bug, with the Java 8 character set used by j.l.Character.
    The regex Unicode tables were synchronized with Unicode 6.3 and
    the Java 8 specific warts were added (and documented).  Most, if not
    all, of these warts have been removed in later Java versions.
    For now, consistency is more important than correctness.

  * Delayed evaluation of tables is implemented to speed up object creation.
    This incurs a slight cost at each first access.

  * Support is added for previously missing Cf (Other, format), Cn (Other
    unassigned) and C (Other) tables.

  * Large tables, such as L (Letter) or C (Other) which are composed
    of sub-tables are now generated.

    This technique could be extended to the sub-tables, but I want
    to commit this PR to establish a historical record of the Unicode
    version (6.3) used and the modification of that date used to
    comply with the Java 8 values used by the Character class.

    A future PR can implement full generation.

  * NOTE WELL: In the course of this PR, I discovered that Unicode
              binary properties, such as White_space are not handled,
	      at all.  There is code in  UnicodeTables.scala which
	      makes it look like they are, but the code to handle
	      those tables in CharClass.scala is __totally_missing__.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
proactively rebased, resolved merge conflict, & scalafmt. Travis CI is all green.

**Comment by ekrich** [comment]
@LeeTibbert Is this something that can be updated and completed?

**Comment by LeeTibbert** [comment]
@ekrich 
> Is this something that can be updated and completed?

Yes, it _could_ be. The underlying change is, IMHO, well worthwhile.  
On a quick re-visit, I think the bit-rot that would have to be fixed
up is the change of `Suite` to `Test`, and the edits that implies.
That is, there is more work, but not years worth, than the
solving the single "Conflicting files".

Unless you ring the fire bell, I do not see myself having time in
the near future (read: months).  I have a number of SN issues in-flight and need
to finish some of them.

**Comment by ekrich** [comment]
This looked like at the time it was pretty much ready to go. I was just looking to see if we could finish/close some PRs. Maybe we should convert some of these to Draft status.

**Comment by LeeTibbert** [comment]
@ekrich  The housekeeping is appropriate and overdue.  I do not like your suggestion to convert to Draft. 

We all know the constraints of available review time. Much as I like this PR and would hate to see my/our
time invested sent to `/dev/null` I think there are more important PRs ahead of it in the queue.
Some of those are for really __emparassing__ issues.  As those
get reviewed and merged or rejected, my plan is to revisit older but still worthy PRs such as this.
That is, keep the silver polished only when someone is about to view it.

Is this PR holding you up in any way?  If yes, I can elevate its priority in my mind.
(Yes, I too would like to retire and reap the results of old sprints)

**Comment by LeeTibbert** [comment]
On the advice of contemporary reviewers, I hope to break this down into a series of
smaller, easier to review, PRs.

**Comment by LeeTibbert** [comment]
The major benefit of this PR is that it has regex use the same Unicode version that is used by
SN j.l.Character.  That is the Unicode 6.3 + JVM warts of JVM, plus some Unicode 13.0 magic
specific to SN.  The baseline re2j port used (and the GitHub repository still uses) Unicode 6.0.0.

The situation before this PR is that a user can, say,  use Character.isLower() to show than some
corner case  character is lower case, but yet regex will fail to match that character as lower case.
This is a huge technical debt and hanging support burden.

This PR is largish, complex, and deals with an arcane topic.  It is one step in the process of 
reducing duplication and conflict between regex and Character.  I believe that it should
be accepted or declined based on "it is better what what exists now and does not introduce
technical debt"  rather than "is it comprehensive & perfect". 
I well know that it is the former, but not the latter.

This PR passes its extensive Test ensemble, which should add confidence.

------------------------------------------------------------------------------------------------------

I spent three or four days trying to factor this PR into smaller, easier to review PRs.
I quickly got to the point of needing to deal with the Unicode 6.0 needing to be
upgraded to Unicode 6.3.  That lead me to changing the Unicode tables, which
led me to situations where I was doing things a second time, but worse, missing
some of the complexities I had found and fixed in this PR.

This PR generates some but not all of the data tables, based on the SN
j.l.Character values. This adds complexity to review, but adds consistency
between the two packages.     

The move to generated tables is incomplete.  For example the L (Letter) table
is generated, but the Ll (lowercase letter) table is not. Conceptually both 
should be. They are not here because the basic concept needed review and
acceptance before investing months of work on completeness.

**Comment by LeeTibbert** [comment]
The concept and the need still exist but the details of this PR have become OBE (Overcome By Events).

**Comment by ekrich** [comment]
Yes, the Characters are now much newer Unicode now.

**Pull request closed without merging**
