### PR TITLE
WIP: Fix #2219: Make TimeTest memory test focused and non-Linux OS friendly.

### LINKED ISSUE #2219: FreeBSD/macOS flaw exists in TimeTest
This is a forget-me-not.

PR 2148 revealed yet another bug in TimeTest,scala.  It reveals itself on non-Linux systems (
at least macOS, and FreeBSD) when used outside of the GMT of the CI environment; that is,
on real user's systems.

So as to not complicate or delay the merge of  PR #2148 I will wait until after it is merged
to submit a fix (which is to simplify the test to only its intended & useful purpose: memory access).

Some gifts just keep on giving!  The underlying flaw the test is set up to detect is particularly
nasty, so it is worth iteratively improving the test, even given the pain.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Test `strftimeDoesNotReadMemoryOutsideStructTm` in TimeTest has
proven to be fragile and sensitive to the operating system on which
it is run.

The test checks that only valid memory is written. We bring clarity
of purpose and jettison the off-topic and troublesome portions of the test.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
I have marked this as WIP.  It is good to go as is now, but merging it before PR #2148 
would force a complicated git re-base.   I will re-base and then remove the WIP in
the title after PR #2148 is merged.

**Comment by LeeTibbert** [comment]
@alexdupre If you have time & interest, could you review the changed test and how it might
impact FreeBSD, and people running outside the GMT CI environment?  Thank you,
either way.

I think/I have nuked the OS dependency there but then I have thought that before. 
This code runs successfully on my private studies towards running CI on FreeBSD.
But then again, my prior code was GMT and ran also ;-)

**Comment by alexdupre** [comment]
@LeeTibbert tested on FreeBSD and it works fine (on CET timezone, w/ and w/o the removal of `%Z` and `GMT` from `strptime`)

**Comment by LeeTibbert** [comment]
@alexdupre Thank you for your time checking this out. Nothing quite like
confirmation from real use.

**Comment by LeeTibbert** [comment]
Closed in favor of PR #2235.

**Pull request closed without merging**
