### PR TITLE
[0.3.x] Add forwarders to support sconfig/scalafmt

### PR DESCRIPTION
**Pull request by ekrich**
This is the first PR in a series to support a Scala Native version of `scalafmt` that needs not be applied to master.

### CODE REVIEW

**Comment by densh** [comment]
I think it's good to prepend 0.3.x-only PR name with `[0.3.x]` to make it clear that it's a backport and/or otherwise a non-master PR.

**Comment by ekrich** [comment]
This is a good idea. I have several more that I would like to target both `0.3.x` and `0.4.0`. They are tested on the former. Once they are accepted, is it ok to rebase and test them against master so they can be applied there as well?

**Comment by densh** [comment]
@ekrich Lets first merge to master and only then backport to 0.3.x.

**Comment by densh** [comment]
LGTM, thanks @ekrich !

**Comment by ekrich** [comment]
Refer to Issue #1412

**Pull request merged**
