### PR TITLE
WIP: Debug javalib InetAddress#getLocalHost Issue 3530

### PR DESCRIPTION
**Pull request by LeeTibbert**
The flaw reported in Issue #3530 occurs in CI but not on my local system.
That means replicating the report and debugging the flaw must occur on CI.

Sorry for the noise and burden on the CI system.

### CODE REVIEW

**Comment by ekrich** [comment]
Looks like you are having fun - did you see this? https://github.com/actions/runner-images/issues/8439

**Comment by LeeTibbert** [comment]
> Looks like you are having fun

Thank you for the encouragement, it helps.  I am well past the point where pain & pleasure
are alloyed.  Basically, I am searching for an intermittent error in a box into which I have
limited visibility (CI configuration) but which has it own quantum foam of intermittent errors.
Any given error, even apparently unrelated, may or may not be caused by my Snark, arrgh!


>  - did you see this? https://github.com/actions/runner-images/issues/8439

I did, whilst poking around in a GitHub blog trying to determine exactly _what_ the macOS network 
configuration is, and if/how it changed from macOS 11 to 12.  Good luck getting such info.

When I read the article the first time, my mind turned off and my hopes were dashed 
when I got to the "paid" part.  

When I get frustrated by waiting for macOS CI, which is often, I try to remind myself when
you, I, and the SN community had _no_ CI, just complaints that macOS features were not working
because they had not been run on macOS. Those were the days.

**Comment by LeeTibbert** [comment]
PR #3551 is the "clean" result of the investigations here.  

I am leaving this WIP PR open, so that I can explore the Windows failing test here.
I seem a similar failure in PR #3551.  I believe the failure is unrelated to the macOS 12 changes
but need to prove that to myself & others.

**Comment by LeeTibbert** [comment]
In the midst of the word he was trying to say,
   In the midst of his laughter and glee,
He had softly and suddenly vanished away—
   For the Snark was a Boojum, you see.

Closed in favor of merged PR #3569.

This WIP PR has done its job.

To sum up, there were two basic flaws and one opportunity for improvement. The
combination of the two flaws lead to the behavior reported in the Issue.

1) GitHub Continuous Integration (CI) macOS 12 (and probably beyond) instances seem to
     consistently have IPv6 on there local network interface. On their interface-to-the world (en0 ?),
     usually have only and IPv4 interface.  Intermittently, they have an IPv6 interface. I could discover
     neither rhyme, reason, or documentation of what the network configuration of an instance should be.

     Having an IP address on an interface other than the local interface, triggers IPv6 handling.  The code
     was doing an IPv6 TCP-only nameserver lookup. IPv4 lookups were getting resolved with IPv4 queries (A records)
     but an IPv6 (AAAA) query was returning the equivalent of "Unknown Host". 

2) Java 8 JDK InetAddress#getLocalHost appears to not throw the `UnknownHostException` when an internet
    address for results of `gethostname()` are not known (Apple "scutil --get HostName" but not exactly, 
    gethostname() there does some fixup deriving the HostName from  LocalHostName if the former is unset.)
    In this case, Java succeeds by returning and InternetAddress containing the supplied hostname and the
    well-known IPv4 loopback address 127.0.0.1.   

    This is a somewhat surprising design decision.

The opportunity for improvement is that previous to the this PR, rolling into PR #3569,
InetAddress name-to-address translation requested addresses for only IPv6 TCP addresses
when IPv6 was enabled. 

Now it will lookup each cell of the 2x2 matrix, IPv6/IPv4, TCP/UDP, honoring the property 
`java.net.preferIPv6Addresses`. This gives a much better chance of retrieving an address
if such exists.

Of course, other name-to-address `quirks` continue to exist on systems with complex configurations.
For example, the resolution of a hostname on a machine with two 'off machine' interfaces with differing internet 
addresses is indeterminate/hard_to_predict (determined by whatever `getaddrinfo()` returns first).

**Comment by kgantchev** [comment]
> When I read the article the first time, my mind turned off and my hopes were dashed when I got to the "paid" part.

Fret not! :) You can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's.

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Pull request closed without merging**
