### PR TITLE
WIP: Chasing Cheshire Cat multiarch linux-arm-64 pidfd_open failure

### PR DESCRIPTION
**Pull request by LeeTibbert**
Trying to determine the recent change which is causing the "Now you see it, now you don't" Cheshire Cat
build failures in multiarch linux-arm-64,  as seen in PR #3478 and others.

### CODE REVIEW

**Comment by He-Pin** [comment]
Will this pr address : https://github.com/scala-native/scala-native/actions/runs/6212069378/job/16862031210?pr=3484#step:7:3265 ?

**Comment by WojciechMazur** [comment]
Isn't that a duplicate of #3485

**Comment by LeeTibbert** [comment]
> Isn't that a duplicate of https://github.com/scala-native/scala-native/pull/3485

This is where I did my scratch work, trying to figure out what changes.  As such
the commit audit trail is both long and confused.  I marked this as both  WIP & Draft
to avoid confusion with the final #3485.   Guess I missed the mark. 

My intent is to close this PR, as soon as #3485 has proven itself.

**Comment by LeeTibbert** [comment]
Closing this PR, as it has done its job, helping me find and fix a build breaker.
Merged PR #3485  has been succeeding for 8 or more inline builds, so I guess
the fix it contains is solid enough to no longer need this scratch space.

Here is to things which go bump in the night!

**Pull request closed without merging**
