### PR TITLE
Add javalib stubs we might support in the future

### PR DESCRIPTION
**Pull request by densh**

### CODE REVIEW

**Comment by ekrich** [comment]
Where are the RMI stubs used or needed?

**Comment by densh** [comment]
[Scala compiler needs those](https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/internal/Definitions.scala#L380).

**Comment by ekrich** [comment]
Super, thanks.

**Comment by sjrd** [comment]
Why would you want these merged? You're going to degrade the experience for normal users. Instead of linking errors, they'll get run-time errors. You don't wanna do that.

**Comment by densh** [comment]
@sjrd 

1. I expect many of those we're going to support in near future.
2. As just discussed offline, we can mark those specially (i.e. `@stub`), and don't link the by default.

**Pull request merged**
