### PR TITLE
Adding missing `java.lang.Character` functionality

### PR DESCRIPTION
**Pull request by j-mie6**
Added `highSurrogate` and `lowSurrogate` to `java.lang.Character` extracted from `toSurrogate`

### CODE REVIEW

**Comment by j-mie6** [comment]
Scala-js does already have `highSurrogate` and `lowSurrogate` implemented. I'll adds some tests in now

**Comment by j-mie6** [comment]
I've signed the CLA, need a new check. What's the lint failing on exactly?

**Comment by armanbilge** [comment]
@j-mie6 I think you need to run `scalafmt` on the files you changed. There is also a script to do so in the `scripts/` folder.

**Comment by j-mie6** [comment]
Should be all good now

**Comment by ekrich** [comment]
@WojciechMazur Can you release this to CI?

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
