### PR TITLE
WIP: Fix #2706: Implement clock & timer routines and test cases

### LINKED ISSUE #2706: posixlib time.scala needs improvment: clock & timer methods & definitions
Recent discussions on Discord brought me to discover that posixlib `time.scala` is missing
a number of commonly used methods & definitions.  The goal would be as complete
as feasible compliance with POSIX `time.h`. Iterative improvement is better than none.
This Issue addresses two groups of methods and punts the completion question to
a day that I will regret later (but not today).

Of course, each group of methods need Tests, if they an be done in economic 
time.

- [ ] `clock_*` methods &  definitions
- [ ]  `timer_*` methods & definitions

This issue will probably take a couple of PR passes.

Linux & FreeBSD have had these methods for a decade or more.
Guards will be put into  `time.c` to detect attempts to compile
on macOS < 10.12, where those methods are missing. Those versions
have been unsupported by Apple for years.

The advantage of this PR is that users will have access to `clock_gettime()`
for CLOCK_MONOTONIC and CLOCK_RUNTIME and two less frequently
used CLOCKs.  Users will still have to 'roll their own' for clib extensions
 CLOCK_REALTIME_COARSE and others.

If posixlib CLOCKs are provided, users will have a working model of the
definition & use of CLOCKs in Scala Native for their private clib extension needs.
Such extensions tend to be operating system specific and are an explicit
non-goal of this Issue.

### PR DESCRIPTION
**Pull request by LeeTibbert**
This PR adds definitions and does not delete any. There is no strict requirement
for SN 0.5.0.

We implement missing `clock_*` and `timer_*` methods and associated definitions.
posixlib `time.scala` is almost completely in compliance with POSIX `time.h`.

There are a few differences and a requirement to link with the link option "-lrt' if
`timer_*` routines are used in non-macOS. The `Library Guide` for `posixlib` has been updated.

Most notably:
 * If any `timer_*` method is used on a non-macOS Platform, the linker option "-lrt"
   must be supplied.

* macOS does not implement `clock_nanosleep` or any of the `timer_` methods.
  Stubs are provided to ease cross platform implementation. These stubs always return -1 
  and set errno to EINVAL.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Moving to WIP. CI is doing its job, finding cases in the supported matrix where code
which worked just fine on my Linux & macOS systems fails.

What is supported, where, & when is, shall we say, complex.
Let me weed through the detritus and fix what I can.
I can then submit a superseding PR with a clean
audit trail.

It looks like the fix is going to be backing out all the `timer_` methods.
They add mega complexity and are for a small specialized audience.
I do not know if `clock_nanosleep` will stay.

More over the next week/weeks, as time becomes available and
frustration wanes.

**Comment by ekrich** [comment]
I found this that could help if you want a mac version - https://speakerdeck.com/jj1bdx/how-i-discover-a-working-implementation-of-clock-nanosleep-for-macos-in-cpan-time-hires

**Comment by LeeTibbert** [comment]
Eric,  Thank you for the URL. I took a quick look at it.  I think that we/I are/am better off with 
a simple stub which return ENOTSUP (not supported).  

`clock_nanosleep()` is entirely outside of the Apple macOS culture.  From the reading I did
looking into trying to provide it, people porting from Linux might expect it only to be
brought up short by the Apple culture.

I think I/we would be putting a lot of effort going down a rabbit hole, only to be
reviled. I think the concept I am going for is beyond "not idiomatic: and
more like "anti-cultural".

I offer one free "I told you so" card,  which can be cashed in at the first "Why does
posixlib clock_nanosleep() always return ENOSUP on macOS" :grinning:

**Comment by LeeTibbert** [comment]
superseded by PR #2713.  CI did its job in this PR by detecting cells in the
configuration matrix which did not work. Evolution identified the multiple
issues (Why would _anybody_ do _that_?) but multiple git commits
complicated the audit trail.  PR @2713 is a clean copy of the
latest evolution of this PR.

**Pull request closed without merging**
