### PR TITLE
Fix CI problems and limit legacy Scala version workflows

### PR DESCRIPTION
**Pull request by WojciechMazur**
* Updates EOL GitHub Actions machines macOS 10.15 -> 11
* Forced installation of clang-14 in multiarch workflows

### CODE REVIEW

**Comment by ekrich** [comment]
Isn't it a little more conservative to use the oldest one supported unless Scala Native really can't support that version anymore?

I am just a bit worried that our code can become a bit too up to date and thus pushing people off the platform if we adopt newer features like the one recently that forces macOS 10.12 or greater. I know that OS version is not supported and not likely to be used but that is the only example I could come up with.

**Comment by WojciechMazur** [comment]
@ekrich good point. Unfortunately, we can never guarantee correct runtime behavior with each available distro version. I wouldn't say that our code is getting too up-to-date, however, like in the case of the failing macOS 12 we should also check that newer versions also work correctly. I think that after all, it wouldn't matter which os version is predominantly used in the CI, as long as we would run at least 1 job with each version available in GitHub actions, including the oldest available one. That would be actually the same strategy as the one we already use for testing legacy Scala 2.11 and 2.12 versions. My plan is to add multi-os-version jobs in the follow-up PR. I assume we might have some problems with Windows 2022 (11) and that's why it was not updating it in this PR.

**Comment by WojciechMazur** [comment]
I've reverted the upgrade to Ubuntu 22.04, after your comment I've concluded it would be better to include it in the follow-up PR

**Comment by LeeTibbert** [comment]
Thank you for the fixes.

When the dust settles in a few days,  perhaps in an Issue
>  Downgrade macOS version 12 -> 11, bue to failing ProcessTest

I see our friend ProcessTest is seeking attention.  I understand
with the high priority work to get _something_ working that you
might not remember the specific failure.   If you do remember
or if I might replicate, what was it?

I ask because `ProcessTest` worked fine on my macOs 12.4 system.
I don't think I have run it on the new 12.5.  Then again, we are
chasing Heisenbugs here.

**Comment by ekrich** [comment]
> I've reverted the upgrade to Ubuntu 22.04, after your comment I've concluded it would be better to include it in the follow-up PR

I just have been bumping versions as they drop them - we should actually work on newer versions that people are using now that you mention it. I didn't have a strong opinion and yes it is better to make progress than worry about every platform being tested or even supported.

**Pull request merged**
