### PR TITLE
Immix : Fix heap end boundary after growing the heap

### PR DESCRIPTION
**Pull request by AlexandreDubray**

### CODE REVIEW

**Comment by densh** [comment]
Review by @valdisxp1

**Comment by valdisxp1** [comment]
Looks good.
Congratulations on finding this. :+1:

**Comment by densh** [comment]
@AlexandreDubray Please go to https://www.lightbend.com/contribute/cla/scala to sign the CLA. Once it's done you can either amend to get a new commit with the same contents and force push it or a dummy empty commit to restart the ci.

**Comment by densh** [comment]
LGTM, thanks @AlexandreDubray and congrats on your first contribution! 👍

**Pull request merged**
