### PR TITLE
Server socket implementation

### PR DESCRIPTION
**Pull request by asoltysik**
Two things missing:
- [x] Proper testing
- [x] Allow custom `SocketImpl` implementations for the method `accept`.

### CODE REVIEW

**Comment by densh** [comment]
Needs squash and rebase due to conflicting changes on master.

**Comment by densh** [comment]
Please rebase your PR on top of latest master due to CI changes, thanks!

**Comment by densh** [comment]
Ping @asoltysik, this PR is blocked by the recent conflicting changes on master.

**Comment by asoltysik** [comment]
@densh done.

**Pull request merged**
