### PR TITLE
[WIP] Initial draft for POSIX aio

### PR DESCRIPTION
**Pull request by ekrich**
The purpose for working on this PR is to provide a basis for implementing portions of Java NIO. Some `struct(s)` rely on pass-by-value so `C` adapters are needed to convert the `struct(s)`. Since these `struct(s)` include `signal.h` `struct(s)` it make sense to implement `signal.h` first or at the same time as `aio.h`. Unless there is some objection, I will add them as one PR.

### CODE REVIEW

**Comment by ekrich** [comment]
@LeeTibbert Sure, I like that style. Are your `sys/types` changes coming to master soon? This is a WIP so I can change when it lands. I try not to add to too many changes to too many files as it gets hard to review - do you have a `sys/types` only PR? If so we could probably get that in and then I could rebase.

**Comment by densh** [comment]
@eatkins sys/types changes have just been merged.

**Comment by densh** [comment]
@ekrich  sys/types changes have just been merged.

**Comment by LeeTibbert** [comment]
@ekrich Looks like you are making progress. If/when I get myself dug out, I will have to take a look
at posix aio documentation.

Two comments, offered in support:
* I'm glad that you concurred with the useage of sys/types.h
* Good to see the placement of aio.c, etc in resources/posix/.  I had to postpone/delay PR #1259 because the wanted to only move file around, and not have their contents change in the same PR
(from prior discussion, I believe that you follow & recommend the same design principal.)  I know that you put aio.c where you did for your own reasons, but it will make my life easier when I revisit PR #1259.  Thank you,

**Comment by ekrich** [comment]
Since aio depends on signal, I am going to remove the signal code from here and open a PR for POSIX signal intending to complete signal first.

**Comment by ekrich** [comment]
This is closed until `signal` gets completed.

**Pull request closed without merging**
