### PR TITLE
Add chdir to posix/unistd

### PR DESCRIPTION
**Pull request by wookietreiber**

### CODE REVIEW

**Comment by wookietreiber** [comment]
I suppose, that error reported by travis is spurious?

**Comment by ekrich** [comment]
Yes, we do see that from time to time.

**Comment by LeeTibbert** [comment]
Devos,

In trying to follow/vet the current PR, I ran across something
which I do not understand.  Please, could someone take
a moment to explain?  

Thank you. A the details of PR I am considering submitting,
adding fork, exec*, wait*, depend my following existing flow. 

nativelib/src/main/scala/scala/scalanative/posix seems to have
three sections.

1) The first section contains straight forward C extern
     definitions. The current PR adds a line to that section.

2) The middle section with has C symbol definitions. 
    I understand why these are re-directed to functions 
   nativelib/src/main/resources/unistd.c.

3) The third section does an @name to a scalanative_
    function in nativelib/src/main/resources/unistd.c

    @name("scalanative_symlink")
    def symlink(path1: CString, path2: CString): CInt = extern

    The target scalanative_ functions all seem to be 
    straight forward passtrough. I am missing something.

    More to the point, does the current PR chdir() need
    such a scalanative_ function?  Would a hypothetical
    future fork() function?

Lee

**Comment by ekrich** [comment]
@LeeTibbert I don't see any reason for the straight pass through delegation. Those `@name` functions are for C constants, any conditional compilation for portability, or for functions that are hard to map directly (pass by value or other translations). We also have a gitter channel :-) https://gitter.im/scala-native/scala-native

**Comment by wookietreiber** [comment]
Great, thx :)

**Pull request merged**
