### PR TITLE
Port to JUnit scala tests

### PR DESCRIPTION
**Pull request by ekrich**
These are all the Scala tests except the ones in the `scalanative` package.

Here is a unified diff since the file names changed: https://gist.github.com/ekrich/f7779ad01a74b18c999c39d08b47fd55

### CODE REVIEW

**Comment by ekrich** [comment]
@sjrd or @WojciechMazur - I was wondering if this could be reviewed. I am going to need to rebase already.

**Review by WojciechMazur — APPROVED** [review]
Looks good to me. The only thing I was thinking about was SymbolTest since the backtick symbol declaration is deprecated in 2.13. I was wondering about making two versions of these tests, one for 2.13+ and the other for older versions, but probably it should be part of the 2.13 branch, instead of this PR.

**Comment by ekrich** [comment]
I think that is a good plan. I have one more batch of tests that I can finish this weekend. After that I guess we could remove the old test suite. 😢

**Review by sjrd — APPROVED** [review]

**Comment by ekrich** [comment]
@WojciechMazur Do you mind putting a ticket in for the backtick issue? I can take care of that after I finish the rest of the tests. I guess this one could be merged too. 😄

**Pull request merged**
