### PR TITLE
Add scripted tests

### PR DESCRIPTION
**Pull request by Duhemm**
Ref scala-native/scala-native#28

### CODE REVIEW

**Comment by densh** [comment]
Is there any way to check that output of the program matches expected value with scripted tests?

**Comment by densh** [comment]
This needs a rebase on top of latest master.

**Comment by Duhemm** [comment]
> Is there any way to check that output of the program matches expected value with scripted tests?

The easiest way is to add assertions in the program's `main`, but one can also write an sbt task that runs the program and checks the output:

```scala
TaskKey[Unit]("checkOutput") := {
  val binary = nativeLink.value.getAbsolutePath
  val output = Process(binary).!!
  if (output.trim != "Hello, world!") error(s"Unexpected output: $output")
}
```

**Comment by densh** [comment]
LGTM, thanks!

**Pull request merged**
