### PR TITLE
Add scalafmt integration

### PR DESCRIPTION
**Pull request by t-hiroyoshi**
Target #131 

`sbtplugin` is ignored because of https://github.com/olafurpg/scalafmt/issues/190

### CODE REVIEW

**Comment by densh** [comment]
Look good apart from the https://github.com/scala-native/scala-native/pull/145. We'll need to merge that one first, and then you'll be able to rebase on top. First commit will have to be thrown away and re-done due to change in the style configuration.

**Comment by densh** [comment]
#145 is merged, this one is next. Please rebase, change first commit and it's LGTM.

**Comment by t-hiroyoshi** [comment]
done!

**Comment by densh** [comment]
LGTM!

**Pull request merged**
