### PR TITLE
Fix #1573, #1544: re2s code and documentation improvements.

### LINKED ISSUE #1573: re2s needs reduced code size
Per discussions with @densh:

The recent re2s regex implementation used two dimensional arrays for Unicode tables
because that is what was in the scala code being ported.  This allowed the
substitution of re2s for cre2 but with known IOUs.

The mid range plan is to unify the Unicode tables in Character & re2s.

There is immediate benefit in both reduced code size reduction and increased access speed
to use the one dimensional tables that were in the original original C code.
Time has come to pay one IOU.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This pull request was motivated by Issue #1573 "re2s needs reduced code
    size". It quickly became evident that Issue #1544 "javalib docs need
    accurate & current description of regex & re2s differences." needed
    to be addressed at the same time, to establish and maintain consistency.

    Issue #1544 is fixed. The major differences have been described.
    Remaining differences will be added as they are discovered.

    The one-dimensional array issue described in #1573 is fixed but
    additional passes are needed to address other opportunities for
    improvement.

    Documentation and implementation should now match.

  * This pull request does not address #1542 "Unicode tables should be
    unified for consistency & minimal binary size". I spent a number
    of days addressing that issue and backed off to create this
    checkpoint. I intend to take another run or 10 on that issue.

    One of the issues is that re2s is based on Unicode ?.?, possibly
    6.? where ? can range from 0 to 3.  I tried to discover the
    version several times, until it became evident that further time
    invested would be neither economic nor prudent.

    Thankfully, Scala Native Character.scala quite plainly documents its
    Unicode version as 7.0.  Java 8, itself, shipped with Unicode 6.2.0.

  * Methods in CharClass.scala and Parser.scala with return statements,
    especially with those returning values, in the middle of the method
    were converted to return only at the end/bottom of the method.
    I am told, on good authority, that returns from the middle of methods
    are currently expensive on Scala Native.

  * The test Suite for j.u.r.Matcher contains a test case to verify
    that Issue #1506 "j.u.regex returns wrong group" if fixed.
    This change comes under the heading of understanding and documenting
    what works and what does not.

    That file was also edited to remove confusing redundant and misplaced
    code.

  * Per request of @densh, renamed package from `scalanative.re2s` to
    `scalanative.regex`.

Documentation:

  * A one line entry in the changelog is requested, probably referring
      to this commit message for details.

  * The file docs/lib/javalib.rst was updated to my best understanding
      of what is and is not supported and implemented in
      java.util.regex and re2s.  

     `sphinx-build` was run and the resultant .html proof-read.

      This was a merge of information from the GitHub re2j and re2s
      repositories and personal investigation and experimentation.
      Despite best efforts, errors may remain.

      That file now documents a change possibly requiring changes in regex
      code when upgrading from Scala Native 0.3.n (n >= 8),
      cre2 based Scala Native 0.3.8 required POSIX patterns of the
      form '[[:alpha:]]'. re2s based 0.4.0 requires the Java
      standard form '\p{Alpha}' and rejects the cre2 form.

Testing:

  * Built and tested ("test-all") in debug mode using sbt 1.2.8 on
    X86_64 only . All tests pass.

  * Built and tested ("test-all") in release-fast mode using sbt 1.2.8 on
    X86_64 only . All tests pass.

  *  `sphinx-build` was run and the resultant .html for javalib proof-read.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
> These documentations should probably say `throws`

@ekrich Thank you for the review & suggested improvement.
You are absolutely correct and I have changed the source as recommended.

**Comment by LeeTibbert** [comment]
> Also, does it make sense or is it possible to translate Java regex patterns to the ones supported by `re2s` if there is a direct mapping?

regex support is going to require wave after wave of improvement.   I think the TL;DR
answer to your question is that it would be possible to translate `\p{javaLowerCase}` and
friends to the corresponding `isLower` etc. but, unless somebody suggests otherwise.
is not at the head of the priority list.    

This evolution I spent quite a bit of time in the RE2 parser. Some of that time was spent
trying to figure out the processing of "is" as in why "isAlphabetic" was unsupported.
Even though I was out of the US at the time, I kept having flashbacks of a certain
US President.  

We are slowly diverging from the RE2s original, to suit SN needs. I think that is OK.
I'll keep 'isJava*" in mind as I continue to try to figure out if and why properties
such as "isAlphabetic" do not work.

**Comment by LeeTibbert** [comment]
Near term futures:

I believe the immediate next wave is to continue chipping away reducing the data overlap
between re2s and j.l.Character. This PR does not reduce that overlap, because I reverted
the work which did. It did however give me experience with the issue.

A near term wave is to roll the changes which have accumulated over the past 18 months
in the re2j master into SN re2s.  One of those changes uses j.l.Character methods to 
eliminate a _large_ re2 data table.  That change triggers Unicode 7.0 related changes 
in other tables, so it is bigger than a bread box.

A third near term wave is to understand why certain patterns do not work in re2s.
Binary properties such as `isAlphabetic` are probably at the top of the list. I do not
understand why the set below do not work and would like to know, if not fix.
At least they are now documented for SN.

```
    Patterns:

        Octal: \0100 - use decimal or hexadecimal instead.
        Two character Hexadecimal: \xFF - use \x00FF instead.
        All alphabetic Unicode: \uBEEF - use hex \xBEEF instead.
        Escape: \e - use \u001B instead.
```

**Comment by densh** [comment]
So on macOS with `nativeMode := "release-fast"` and `nativeLTO := "thin"`, the binary size for simple hello world that uses regex (calls to `replaceAll`) goes down from 2.99Mi to 2.15Mi. That's a giant drop!

**Comment by LeeTibbert** [comment]
> So on macOS with `nativeMode := "release-fast"` and `nativeLTO := "thin"`, the binary size for simple > hello world that uses regex (just calls to `replaceAll`) goes down from 2.99Mi to 2.15Mi.
> That's a giant drop in binary size! clap

Thank you for this information. It is good to have actual data.  The reduction makes me feel
like the work was worthwhile.

Progress report.
I am working on further reductions in strictly re2s/regex. @ekrich and I have also been
coordinating with reducing overlap between Character and re2s/regex

**Comment by LeeTibbert** [comment]
> In the spirit of #1602, I'd recommend renaming `scalanative.re2s` to `scalanative.regex`.
> As you mentioned in the comments, we start to diverge from re2s and it's a good thing.
> We'll tailor the code to our needs rather than being just a port of re2j.

I concur with the name change and think it to be for the better. Other changes I am
working on for re2s/regex will cause further divergence, so the name change gives
me a better feeling. My User Interface friends talk about the concept of `affordance`,
basically a clue. `regex` gives a better affordance.

I'll switch gears and make the changes.

**Comment by LeeTibbert** [comment]
Change from scalanative.re2s to scalanative.regex made as requested.  Travis CI reports all green.

I checked javalib.rst and there appeared to be no required change.

**Comment by densh** [comment]
LGTM, thanks @LeeTibbert ! 👍

**Pull request merged**
