### PR TITLE
Implement javalib ZipFile stream method

### PR DESCRIPTION
**Pull request by LeeTibbert**
This is a partial fix for Issue #3748, which should remain open.

Implement the  `stream() method of javalib `java.util.zip.ZipFile` and a corresponding
unit-test.

<hr \hr>

  * I am reasonably confident in these changes but would like to see them  get reviewed and exercised 
    in preliminary `jdk.zipfs` work before rolling them, _mutatis mutandis_,  into `JarFile`.

  * For the same reason, I think it wise to hold off porting these changes to the SN 4.n
branch for a few weeks.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Several `Zip` and `Jar` tests fail, so I am pulling this off onto a side spur line.

**Comment by LeeTibbert** [comment]
The Tests of this PR now run.  

The four failing tests seem to be variations of "I'm going to fail and leave nothing in the log file.
Catch me if you can.

**Review by WojciechMazur — APPROVED** [review]
LGTM

> The four failing tests seem to be variations of "I'm going to fail and leave nothing in the log file.

Actually 3 of them are failing with some information, there's a short message about termination due to SIGILL - it's frequent issue on MacOS. No idea why it happens, or how to debug it. Anyhow it's not related to this PR

**Comment by LeeTibbert** [comment]
Thanks for the merge and the info about `SIGILL`.  

I'll grep for that in the future.  

Off the top of your head, is the intermittent `SIGILL` usually/more_frequently on runs
with RELEASE_FAST and LTO?    For a long time, that combination did not work at
all on macOS.

I do my most of my development on a mac M1 and have never see it.  Of course, now
that I have said that, it will start popping up.

**Pull request merged**
