### PR TITLE
Add constant folding

### PR DESCRIPTION
**Pull request by hkapp**
Add constant folding as a new pass.

Does anyone see an op for which we would need to explicitely handle overflows ?

### CODE REVIEW

**Comment by sjrd** [comment]
You need to be careful with integer `/` and `%` by 0. That should not crash the compiler.

**Comment by hkapp** [comment]
@sjrd Yes, definitely. I'll double check, but I think these are all handled. I should also add tests for that. Now, is there any other case where the evaluation can throw, e.g. some overflow exception ?

**Comment by sjrd** [comment]
> Now, is there any other case where the evaluation can throw, e.g. some overflow exception ?

No, there is no other exception anywhere.

**Comment by densh** [comment]
LGTM!

**Pull request merged**
