### PR TITLE
Attempt to use `ar` command for static libraries when possible

### LINKED ISSUE #3542: Consider defaulting to `ar` command for static linking, instead of llvm-ar
Currently we hard request `llvm-ar` and corresponding `LLVM_BIN` installation to be available.
This causes friction in environments where we use the globally installed clang.

`ar` command can do the same things (with object files, not LLVM bitcode), but it's available by default. 

I propose we try to use `ar` if `llvm-ar` is not available.

https://sourcegraph.com/github.com/scala-native/scala-native/-/blob/tools/src/main/scala/scala/scalanative/build/LLVM.scala?L255:37

### PR DESCRIPTION
**Pull request by keynmol**
Closes #3542

### CODE REVIEW

**Review by WojciechMazur — APPROVED** [review]
Thank you for this change, looks good to me. Could please only rebase this branch on the current HEAD just to be sure? At the time it was submitted the mac-os CI was broken, sorry for that.

**Comment by keynmol** [comment]
@WojciechMazur seems like my dynamic lib PR was merged with a failure: https://github.com/scala-native/scala-native/actions/runs/6439525000/job/17488991160#step:4:342

I will investigate and provide a fix in this PR.

**Comment by keynmol** [comment]
If you need help backporting this into 0.4.x - please let me know, I really want to get this into the next release, just to avoid setting up LLVM on Scala-cli :D https://github.com/VirtusLab/scala-cli/pull/2196#discussion_r1350344871

**Comment by WojciechMazur** [comment]
Sorry about merged that one too early. Only this PR seemed to be able to break something. Should have waited for the rebase and not skip the procedure

**Comment by WojciechMazur** [comment]
> If you need help backporting this into 0.4.x - please let me know

I think it should apply quite smoothly, but I won't hesistate to ask for clues if needed. Thank you. I'd like a make a next 0.4.x patch by the end of this week

**Pull request merged**
