### PR TITLE
Implemented AtomicXXX and YYYReferences in javalib

### PR DESCRIPTION
**Pull request by musabilal**

### CODE REVIEW

**Comment by densh** [comment]
@musabilal, commit message mentions AtomicXXX but those are not mentioned in the code. Did you leave them out by accident?

**Comment by densh** [comment]
This PR needs some love from `bin/scalafmt`.

**Comment by MasseGuillaume** [comment]
@musabilal Scala.js source for atomic: https://github.com/scala-js/scala-js/tree/master/javalib/src/main/scala/java/util/concurrent/atomic

**Comment by densh** [comment]
Also needs `// Ported from Scala.js.` comment as discussed in https://github.com/scala-native/scala-native/pull/431#discussion_r91926193.

**Comment by musabilal** [comment]
I have 
1. added code for AtomicXXX 
2.ran bin/scalafmt for the added code
3. added comment "// Ported from Scala.js." for the commit

**Comment by densh** [comment]
LGTM, thanks!

**Pull request merged**
