### PR TITLE
Make CHA completely eager

### PR DESCRIPTION
**Pull request by densh**
Instead of doing lazy completion like scalac, we instead sort
definitions in topological order and complete them eagerly.

### CODE REVIEW

**Comment by densh** [comment]
This brings us to sub-second `nativeLink` on sandbox after 7 warm-up iterations:
```
[info] Loading project definition from /Users/Denys/.src/native/project
[info] Compiling 1 Scala source to /Users/Denys/.src/native/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to native (in build file:/Users/Denys/.src/native/)
[info] Linking NIR (408 ms)
[info] CHA (136 ms)
[info] Optimizing NIR (897 ms)
[info] Generating LLVM IR (307 ms)
[info] Compiling LLVM IR to native code (396 ms)
[info] Total (2198 ms)
[success] Total time: 2 s, completed Feb 19, 2017 3:46:43 PM
[info] Linking NIR (185 ms)
[info] CHA (51 ms)
[info] Optimizing NIR (525 ms)
[info] Generating LLVM IR (166 ms)
[info] Compiling LLVM IR to native code (357 ms)
[info] Total (1299 ms)
[success] Total time: 1 s, completed Feb 19, 2017 3:46:44 PM
[info] Linking NIR (175 ms)
[info] CHA (46 ms)
[info] Optimizing NIR (518 ms)
[info] Generating LLVM IR (88 ms)
[info] Compiling LLVM IR to native code (402 ms)
[info] Total (1236 ms)
[success] Total time: 1 s, completed Feb 19, 2017 3:46:46 PM
[info] Linking NIR (154 ms)
[info] CHA (42 ms)
[info] Optimizing NIR (447 ms)
[info] Generating LLVM IR (93 ms)
[info] Compiling LLVM IR to native code (385 ms)
[info] Total (1128 ms)
[success] Total time: 1 s, completed Feb 19, 2017 3:46:47 PM
[info] Linking NIR (149 ms)
[info] CHA (40 ms)
[info] Optimizing NIR (440 ms)
[info] Generating LLVM IR (100 ms)
[info] Compiling LLVM IR to native code (372 ms)
[info] Total (1112 ms)
[success] Total time: 1 s, completed Feb 19, 2017 3:46:48 PM
[info] Linking NIR (149 ms)
[info] CHA (41 ms)
[info] Optimizing NIR (392 ms)
[info] Generating LLVM IR (76 ms)
[info] Compiling LLVM IR to native code (361 ms)
[info] Total (1026 ms)
[success] Total time: 1 s, completed Feb 19, 2017 3:46:49 PM
[info] Linking NIR (149 ms)
[info] CHA (40 ms)
[info] Optimizing NIR (375 ms)
[info] Generating LLVM IR (60 ms)
[info] Compiling LLVM IR to native code (356 ms)
[info] Total (986 ms)
[success] Total time: 1 s, completed Feb 19, 2017 3:46:50 PM
```

**Comment by densh** [comment]
Unit tests improve to, down to 1.8 after 7 runs:
```
[info] Loading project definition from /Users/Denys/.src/native/project
[info] Set current project to native (in build file:/Users/Denys/.src/native/)
[info] Linking NIR (843 ms)
[info] Optimizing NIR (1546 ms)
[info] Generating LLVM IR (594 ms)
[info] Compiling LLVM IR to native code (629 ms)
[info] Total (3843 ms)
[success] Total time: 4 s, completed Feb 19, 2017 3:50:51 PM
[info] Linking NIR (470 ms)
[info] Optimizing NIR (921 ms)
[info] Generating LLVM IR (216 ms)
[info] Compiling LLVM IR to native code (662 ms)
[info] Total (2343 ms)
[success] Total time: 2 s, completed Feb 19, 2017 3:50:53 PM
[info] Linking NIR (406 ms)
[info] Optimizing NIR (685 ms)
[info] Generating LLVM IR (159 ms)
[info] Compiling LLVM IR to native code (641 ms)
[info] Total (1964 ms)
[success] Total time: 2 s, completed Feb 19, 2017 3:50:55 PM
[info] Linking NIR (344 ms)
[info] Optimizing NIR (620 ms)
[info] Generating LLVM IR (167 ms)
[info] Compiling LLVM IR to native code (624 ms)
[info] Total (1819 ms)
[success] Total time: 2 s, completed Feb 19, 2017 3:50:57 PM
[info] Linking NIR (398 ms)
[info] Optimizing NIR (602 ms)
[info] Generating LLVM IR (170 ms)
[info] Compiling LLVM IR to native code (644 ms)
[info] Total (1872 ms)
[success] Total time: 2 s, completed Feb 19, 2017 3:50:59 PM
[info] Linking NIR (347 ms)
[info] Optimizing NIR (611 ms)
[info] Generating LLVM IR (126 ms)
[info] Compiling LLVM IR to native code (578 ms)
[info] Total (1719 ms)
[success] Total time: 2 s, completed Feb 19, 2017 3:51:01 PM
[info] Linking NIR (344 ms)
[info] Optimizing NIR (597 ms)
[info] Generating LLVM IR (125 ms)
[info] Compiling LLVM IR to native code (641 ms)
[info] Total (1764 ms)
```

**Comment by DarkDimius** [comment]
@densh, how much is it after than the previous approach?

**Comment by densh** [comment]
@DarkDimius I've just added current master numbers above

**Pull request merged**
