### PR TITLE
Add toString implementation to Enum

### PR DESCRIPTION
**Pull request by soc**
This should fix the following error:

```
Unresolved dependencies:
  `@java.lang.Enum::toString_class.java.lang.String`
```

### CODE REVIEW

**Comment by soc** [comment]
@densh Is there a way to see _how_ the source code is misformatted?

**Comment by sjrd** [comment]
@soc Can't you simply run `scalafmt` before re-committing?

**Comment by soc** [comment]
@sjrd I'm on it, I was hoping to be able to do a drive-by fix ... I have now checked out the repo locally and looking into it.

**Comment by soc** [comment]
```
[trace] Stack trace suppressed: run last sbtplugin/compile:scalafmt for the full output.
[error] (sbtplugin/compile:scalafmt) java.lang.NoSuchMethodError: scala.Option.contains(Ljava/lang/Object;)Z
```

**Comment by soc** [comment]
I ran it just on that file, and the result looks exactly like what I had in my first commit.

**Comment by soc** [comment]
`scalafmtTest` runs successfully on my machine.

**Comment by densh** [comment]
Here is the diff I get if I run `sbt scalafmt` on your branch:
```diff
--- a/javalib/src/main/scala/java/lang/Enum.scala
+++ b/javalib/src/main/scala/java/lang/Enum.scala
@@ -3,8 +3,8 @@ package java.lang
 abstract class Enum[E <: Enum[E]] protected (_name: String, _ordinal: Int)
     extends Comparable[E]
     with java.io.Serializable {
-  def name(): String = _name
-  def ordinal(): Int = _ordinal
+  def name(): String              = _name
+  def ordinal(): Int              = _ordinal
   override def toString(): String = _name
-  final def compareTo(o: E): Int = _ordinal.compareTo(o.ordinal)
+  final def compareTo(o: E): Int  = _ordinal.compareTo(o.ordinal)
 }
```

**Comment by soc** [comment]
OK, then I'll change it to look like this because I can't reproduce it.

**Comment by soc** [comment]
Sorry for all this noise, new PR: https://github.com/scala-native/scala-native/pull/310

**Comment by densh** [comment]
@soc No worries!

**Pull request closed without merging**
