### PR TITLE
Issue #382: Box and unbox results of function pointers

### PR DESCRIPTION
**Pull request by hubertp**
When using the values of function pointers boxing (or lack of it) introduced
by the Scala compiler interacts in a  weird way with the nir code gen phase.
For proper boxing instructions, integer and float types of values now have to carry
around the information about the initial Scala type (to distinguish between
the integer values that have the same bit-length).

### CODE REVIEW

**Comment by densh** [comment]
Storing more information in the NIR for the primitive types is something I've been thinking of for a while. This PR is definitely a step in right direction.

But how about we just mirror front-end view of primitive types instead of having a LLVM-style `iN`/`fN` types? This seems to be a bit simpler than ConvFroms approach proposed in this PR.

More specifically what I mean:

1. Replace our current numeric primitives `i8, i16, i32, i64, f32, f64` with `Byte, Short, Int, Long, UByte, UShort, UInt, ULong, Float, Double, Char`. 

2. Arithmetic operations now don't need to encode signed-ness, it can be deduced from the type now. So `nir.Bin.{Iadd, Fadd, Isub, Fsub, Imul, Fmul, Sdiv, Udiv, Fdiv, Srem, Urem, Frem, Shl, Lshr, Ashr, And, Or, Xor}` can become `nir.Bin.{Add, Sub, Mul, Div, Rem, Shl, Lshr, Ashr, And, Or, Xor}`.

Given that it's not the main focus of this PR we can delay it for later.

**Comment by densh** [comment]
**P.S.** Also needs a rebase on top of latest master.

**Comment by densh** [comment]
Anyway, the approach taken here works, we can improve it further later on. 

I've rebased this PR on top of latest master in https://github.com/scala-native/scala-native/pull/504

LGTM! Thanks @hubertp! 🍰

**Comment by hubertp** [comment]
@densh Thanks, I was a bit out of the loop for a while. I will have a look into further improvements.

**Pull request closed without merging**
