### PR TITLE
Port `CopyOnWriteArrayList` from Scala.js

### PR DESCRIPTION
**Pull request by armanbilge**
Targeted to 0.4.x.

### CODE REVIEW

**Comment by armanbilge** [comment]
I'm confused by the failure.
```
Error:  nir: Failed binary compatibility check against org.scala-native:nir_2.12:0.4.5! Found 1 potential problems
Error:   * object scala.scalanative.nir.Attr#Volatile does not have a correspondent in current version
Error:     filter with: ProblemFilters.exclude[MissingClassProblem]("scala.scalanative.nir.Attr$Volatile$")
Error:  java.lang.RuntimeException: Failed binary compatibility check against org.scala-native:nir_2.12:0.4.5! Found 1 potential problems
```

**Comment by LeeTibbert** [comment]
Thank you for the Scala.js commit & date tags.  They __really__ help the next generation who has
to maintain ports.

**Comment by ekrich** [comment]
> I'm confused by the failure.
> 
> ```
> Error:  nir: Failed binary compatibility check against org.scala-native:nir_2.12:0.4.5! Found 1 potential problems
> Error:   * object scala.scalanative.nir.Attr#Volatile does not have a correspondent in current version
> Error:     filter with: ProblemFilters.exclude[MissingClassProblem]("scala.scalanative.nir.Attr$Volatile$")
> Error:  java.lang.RuntimeException: Failed binary compatibility check against org.scala-native:nir_2.12:0.4.5! Found 1 potential problems
> ```

I don't see anything you have changed to cause the incompatibility. Are you sure your environment is clean? Takes a while but I would try `+clean`.

**Comment by armanbilge** [comment]
@ekrich thanks for the tip, but I don't see how cleaning my local workspace will solve a CI failure :)

Indeed, it looks like a more serious problem. Seems like v0.4.5 was published with a mixture of 0.5.x development stuff in it.
- https://github.com/scala-native/scala-native/issues/2733

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
