### PR TITLE
Implementation for part of java atomics

### PR DESCRIPTION
**Pull request by Korf74**
This PR contains part of java.util.concurrent.atomic, it uses CAtomics introduced in a previous PR.

### CODE REVIEW

**Comment by Korf74** [comment]
seems like CI crashed on OSX with immix

**Comment by densh** [comment]
@Korf74 Just restarted it!

**Comment by densh** [comment]
Please rebase your branch on top of latest topic/multithreading due to CI changes.

**Comment by Korf74** [comment]
@densh Travis fails on scalafmt but it works fine locally (and with immix test)

**Comment by densh** [comment]
Thanks, @Korf74 !

**Pull request merged**
