### PR TITLE
Fix Issue #481 "java.lang.{Float, Double}::toString is inconsistent with Scala JVM

### PR DESCRIPTION
**Pull request by LeeTibbert**
* The presenting issue, #481, described one inconsistency between
    {Float, Double}::toString and the JVM but closer inspection revealed
    a number of similar issues, same cause.  All of these are fixed
    in this Pull Request. Associated and affected tests suites are also
    fixed.

  * This code is a heavily modified version of the Ryu fast toString
    code by Ulf Adams, posted at https://github.com/ulfjack/ryu.
    The original paper can be found at URL:
    https://dl.acm.org/citation.cfm?id=3192369

    As a derivative work, the Ryu*.scala files carry the appropriate
    Apache license & modification notices.

    Thank you Densh for suggesting this approach.

  * This is a breaking change.

  * The current code matches JVM output in all of the many cases tried.
    As this code is exercised in the wild, please be on the lookout for
    issues with accuracy in least significant (or other) digits and,
    especially, rounding mode.

    This code uses the IEEE754 HALF_EVEN (.5 to closest even number).
    In all cases I have tried, the Scala JVM results match this mode.

    I have seen references that Java uses HALF_UP (.5 away from zero)
    but have not been able to spot differences.

    I have not done any testing against Java directly. It may be
    that Scala JVM and Java use slightly different rounding modes.

    If you manage to spot a difference, please report it. Thank you.

    This is a, possible, issue with display. The underlying values
    are correct (and un-rounded).

  * The original Ryu code is still changing at a rapid rate. It will
    probably need to be re-ported in six months or so.  The current
    code still provides value.

  * Because the Ryu code will need to be re-ported soon, the Ryu.scala
    code looks like C code which was ported to Java code which was
    ported to Scala code.

    I made no attempt to do optimizations, such as removing the
    computation of results which are never used. I suspect that the
    ScalaNative compiler can not currently do that on its own.
    I also made no attempt to transliterate into idiomatic Scala code.

  * An alternate approach was considered and abandoned. For three or so
    weeks I tried to get the obvious approach of Double.scala calling
    into java.text.DecimalFormat.scala to work.  I encountered a
    large number of implementation infelicities. At the end of the
    effort I had sandbox code mostly working but it had obvious, and
    to my mind, fatal, problems with numerical accuracy. Would you
    trust code which printed out wrong least significant digits, plural,
    for the known Double.MaximumValue.

    I did not do timing measurements on either the DecimalFormat or
    Ryu approach but from the sheer volume of code executed to get
    wrong results in the former, the Ryu approach has to be faster

  * The current approach of having Double.scala and Float.scala call
    directly into Ryu IEEE754ToString code introduces an
    inconsistency with String.format(), which calls Formatter.scala
    which, I believe, calls the problematic DecimalFormat code.

    DecimalFormat can, and should, be changed to call into the
    Ryu code. The DecimalFormat API requires it to handle specified
    minimum and maximum number of fraction digits. DecimalFormat
    can use the Ryu code to get correct basic information, but must
    transform it to meet its requirements.

    Changing DecimalFormat to use Ryu is a bigger-than-a-breadbox
    problem and is left for further work.  I would like to see
    the Ryu code get exercised for a while.

  * For future reference... This code passes all current tests.
    It breaks the StatUtils.format() method in the now retired
    benchmarks sub-project file:
        benchmarks/src/main/scala/benchmarks/Formats.scala

    I did a quick check of the new GitHub S-N benchmarks project and
    it appears the code has changed so much it should not be affected.
    I _have_not_ run that the new benchmarks project using the code
    in this pull request.

64/32 bit issues:

      None known for systems where IEEE754 floating point values and
      integers have the same endedness.  I will check with Shadaj
      on gitter to see if there might be any issues with ARM.

Documentation:

      Deserves a release note.

Testing:

	* Built and tested ("test-all") on X86_64 and X86.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
As a bonus this PR also partially fixes issue #1071.

**Comment by LeeTibbert** [comment]
@densh 

Your review & comments come at a good time. In the next week or so, I hope to port over
a small performance change in RYU and will have to re-qualify this entire PR.

I understand & entirely support your desire to get changes as assuredly right as
possible the first time.  I would not want to needlessly embarrass either myself
or the project.  

#### Tiered testing
To keep this PR reply reasonably on track & to invite discussion from others, I will
create an issue to discuss what I will call tiered testing.  That is, time & compute intensive
testing which happens, say, once a month or once a release cycle, but not in the CI after
every PR commit, related or not.

#### Testing of this PR

Can we discuss how to proceed with testing this PR to the point were it is acceptable?

The code you see in the test suite is only a minor part of the testing I did for this PR.
The code you see is a vastly reduced set of the white box testing I did. The test cases
were selected to cover the basics yet run quickly in CI.  

I also did black box stochastic testing.  

The best reference I could find was the JVM itself.  The RYU c test code 
tests the printf not JVM format.  If I remember correctly, the RYU java format was
minimal to non-extant. I could check that.  I believe I gave a quick look at
porting the Harmony test code.

I tested at various numbers of iterations,  proving myself up the ladder.  On each iteration,
 I compared a Double in the range  (MinPositiveValue, MaxValue] to the value returned by the JVM. 
I created white box tests. many of which are in this PR. to cover endpoints and other interesting cases

Several times I did runs of 10 million iterations.  Time for the run was what stopped me,
not correctness.

In each case, the IEE754 "guaranteed good" significant digits (long discussion omitted here) 
generated by scala RYU code matched those generated by the JVM.  There were a small number,
probably less than 100 in a 10 million iteration run, where there were differences in the
known to be inaccurate non-significant digits.  

While I can not guarantee that there are no errors in the current code, I am reasonably confident that
it can be released to a small audience.  Every new class of user uncovers a new class of bugs....

I did not clean up and submit my stochastic code because I did not want to add 10 minutes
or an hour to each and every CI run   .

#### Possible next steps.

I would appreciate your guidance for next steps.  A few that I can suggest to build
confidence.

* The RYU c code has some tests for "known hard/corner cases", similar to some of the
tests scala-native has for fixed issues.  I could port those (50?) cases to scala and JVM
format. The tests should add seconds to the existing unit-tests.   

* I could add tests to my private development stochastic Double tests to generate
  * negative values for Doubles
  * values (+ and -) for Floats.

* I could run my black box testing with different seeds
* I could run my black box tests for a few hours or a day 
    
* I could study what it would take to do tiered testing, and then write a proposal.

Please advise. Thank you.

**Comment by densh** [comment]
@LeeTibbert It looks like a merge gone a bit wrong, can you please your changes on top of current master?

**Comment by LeeTibbert** [comment]
Agreed, looks like I messed up a rebase to current master.  Sorry!  

Looks like it would be simpler for all involved if I closed this issue and created
a new one from current master.  It means losing the conversation here, but
that is probably a necessary loss.

@densh If you concur, I will proceed that way after one last commit here (so I do not
lose it).

**Comment by densh** [comment]
It's perfectly fine to reopen a PR. You can link to the older discussion by mentioning this PR in the description of the new one.

**Comment by LeeTibbert** [comment]
I've changed this to a Work in Progress (WIP).   The changes work as intended, especially after today's commits, and pass all tests: current mainline, new S-N style DoubleSuite.scala & FloatSuite.scala cases and new RYU style DoubleRyuSuite.scala & FloatRyuSuite.scala.

The S-N code is not at par with the Ryu code for correctness, to the best I can prove to myself.
I have not checked the S-N code for performance versus the RYU java code.

Unfortunately, I appears that my attempts to do a re-base really mess up the number of files
wanting to be merged.  I had hoped that they would get squashed or such, but no luck &
insufficient skill/knowledge.


Enough for the day.  I will attempt to create a fresh PR based on current S-N mainline
in a future sprint.

**Comment by LeeTibbert** [comment]
Superseded by PR #1436. That PR isolates the intended changes.

**Pull request closed without merging**
