### PR TITLE
Remove non local returns from java.net.URI

### PR DESCRIPTION
**Pull request by ekrich**

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Wow!  This fix is way simpler than anything I had been considering/fearing.  I was seeing 16 of the "non-local return"
warnings and thought I was going to have to fix them one by one.  Looks like you found a much better
implementation point or points.

I copied this to my local system and ran 3.2.0 tests.  With this fix and our earlier Primality fix, I see 
zero  "non-local return"  warnings. A big "Thank you".

 I believe you can mark Issue #2822 as fixed by this.

**Review by LeeTibbert — APPROVED** [review]
LGTM - Looks good to me

I say thank you now and I will be saying "thank you" over and over as I am doing
javalib development.

**Comment by ekrich** [comment]
After looking at some code in Scala.js which has the toughest standards, you can see them use occasional `return`s. Sometimes that is even easier to read. This one is pretty ugly (sorry to the person who wrote it) so I am just thankful I didn't have to write it from scratch.

**Comment by LeeTibbert** [comment]
Mostly for the benefit for future readers:

I think most or all of the offending "returns" and possibly some non-offending ones are in 
two "isValidIPvN" tests, one for IPv4 and one for IPv6.  Now 'InetAddress.getByName()'
already does that parsing. That code is much better exercised than `URI.scala`
and likely to be less buggy.

I believe that the current `URI.scala` code will fail to parse certain valid IPv4 cases.
I would put lunch money on it failing any reasonably comprehensive IPv6 test suite.

Worst case, one could port the posixlib `pton()` method to `clib`, and call it.
That is the routine called by `InetAddress` and is pretty much the definition
of what is and is not a valid IPvN address.   

There is a place for 'roll your own', but it has costs & defects.



One could

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
