### PR TITLE
fixed a bug with Math.min on Doubles

### PR DESCRIPTION
**Pull request by gregor-i**

### CODE REVIEW

**Comment by densh** [comment]
[Please sign Scala CLA to continue](https://travis-ci.org/scala-native/scala-native/jobs/191897225#L394).

**Comment by gregor-i** [comment]
Hi Denys. I just signed the CLA. How do I restart the travis?

**Comment by densh** [comment]
Next step: add some unit tests under `unit-test/` folder. Testing that other functions in `java.lang.Math` work would be super helpful too.

**Comment by densh** [comment]
I've restarted travis build.

**Comment by sjrd** [comment]
FTR: https://github.com/scala-js/scala-js/blob/v0.6.14/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/MathTest.scala#L35-L69

**Comment by densh** [comment]
LGTM, thanks @gregor-i !

**Pull request merged**
