### PR TITLE
Implement shutdown using atexit instead of c++

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by sjrd** [comment]
Are there any trade-offs, here? Or is this 100% win?

**Comment by lolgab** [comment]
From my tests they behave the same way.
Maybe a review from @eatkins would be helpful.

**Comment by LeeTibbert** [comment]
@lolgab    

I believe this PR introduce a behavior change which is almost impossible
to detect on reading but which will cause the Devil's own time to debug.

You might want to consider/exercise cases where the function being executed by atexit()
contains a runtime error. One case  where it throws a Scala Exception, a second where it throws
a C++ Exception, and a third where it causes a C signal (libc.strlen(null)).

I suspect, but do not know, that with the current code an uncaught exception will 
get reported by a SN/libunwind last chance handler as a stack trace in the first two.
The third case will silently die in the night.

I suspect that with this PR, all three will silently die in the night.

We all probably agree that trying to track down errors atexit() is a bear at the 
best of times. If, as I suspect, this PR causes SN to no longer have stacktraces
for errors within the executed function, debugging will be much harder.

The SN initialization code, equivalent to crt0, currently does not, I believe, establish
C signal handlers. Yes, there are some signals which can not be caught...  I have
been chasing a similar problem in the test environment, where a test which
causes a C signal causes TestMain to silently disappear: poof!

At one point this past Summer, I had some sandbox code which established
a handler for at least Sigfault.  There was lots of change going on in the
test environment, so I never advanced that code to a PR.  My thought
at the time was that if it proved out, I would then look into the SN 
initialization code to see about adding some C signal handlers.

My pending PR #1831 and the issue it solves has some discussion
which might be relevant about the joys of mixing C signals and
C++/SN Exceptions.

**Comment by eatkins** [comment]
@lolgab I am planning to retire from scala open source after the sbt 1.4.0 release which is coming soon. Good luck with Scala Native though!

**Comment by lolgab** [comment]
Hi @LeeTibbert,
I tested myself and I can't find differences. They both skip the `try { } catch { }` present in Scala Native `main` and if you throw an exception without catching it they will crash without stacktraces:
```
libc++abi.dylib: terminating with uncaught exception of type scalanative::ExceptionWrapper: std::exception
```
Since the `Shutdown.addHook` is used only to delete files, the exceptions are voluntarily catched without any logging [here](https://github.com/scala-native/scala-native/pull/1906/files#diff-43ebbfd71f646f47cbb3d0d40972ff67R15).
Do you have a reproduction where they give with different results?

@eatkins It is very unfortunate for the Scala community that you're going to retire from Open Source. I understand there are other things in life and I wish you the best for your future, while thanking you for all the good things you did for Scala Native and for sbt.

**Comment by LeeTibbert** [comment]
Off topic:
@eatkins I wish you the best in your next chapter.  Your code has always been clean, useful, & instructive.   There are a couple of your changes to sbt (such as, I believe, reload on changed build.sbt) that I bless every hour.

On topic:

Sounds like you have done due diligence and addressed my concern of "do no harm".
I think the PR should proceed, in the fullness of time.

I believe the skipping of the `try/catch` is an indication that something is not quite right
in that initialization code. That is, some lack of robustness about the difference between
Exceptions and C signals or in the lib$unwind handling.   Anyway, that is a different
issue than you are trying to resolve here.

Although I am bothered by the lack of robustness, and have been experiencing it,
at lest in TestMain, for years, I think it of greater benefit to SN if I focus on my
current work providing pieces in SN which will be needed by applications in order
to port to SN 0.next.   I would _love_ focus on writing a few exploratory
test cases here, because I think/suspect a Florida sized insect or nest.

I'll keep a few mental tripwires out. Faults on initialization, fault, or shutdown paths are
always hard to catch.

Thank you for considering & addressing my concerns.

**Comment by eatkins** [comment]
@lolgab and @LeeTibbert Thanks for the well wishes! I am glad to hear my work has been helpful.

**Review by ekrich — CHANGES_REQUESTED** [review]
I think this PR is fine. `atexit` is just for normal exit. The code is simpler as well. Could you rebase and run with the new `scalafmt` setup.

**Comment by WojciechMazur** [comment]
Agree, I've used it recently for some ScalaNative demo and it works fine, I have not seen any downsides.

**Comment by lolgab** [comment]
@ekrich @WojciechMazur Thank you for looking at it.
I rebased as suggested and ran `scripts/scalafmt` to ensure there aren't formatting changes.

**Review by ekrich — APPROVED** [review]
LGTM pending review by @WojciechMazur

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
