### PR TITLE
[WIP] Fix #1258: Make posix file locations in C and scala code parallel

### LINKED ISSUE #1258: nativelib/src/main/resources cries out for housekeeping
Let me capture an issue I noticed during my recent PR sprint.  The PR I was working on
at the time was growing too large and complex, so I am resorting to creating an issue
so that I can remember it when/if I have time to return.

The great Swiss child psychologist Jean Piaget described a process of child development where the child first accommodates then assimilates.  In the accommodation stage, new concepts are stuffed in to the existing cognitive schema. After a while, enough concepts are added that the schema becomes unstable, forcing the child to re-organize, integrate, and adopt a new schema.  Soak, wash, rinse, repeat.

Now, you ask, what does this have to do with scala-native and why am I darkening your doorstep?

It looks like nativelib/src/main/resources has grown through the folk process; change upon change with minimal re-organization.  Not complaining, just describing and seeing an opportunity for improvement.

There is a resources/posix subdirectory tree but many posix files, fcntl,c, stat,c, unistd.c, and others, exist at the top level, not in the posix tree. Not only does this make files hard to find, it means that the organization of the C code does not parallel the nicely organized posix scala code. Software engineers get troubled by such apparently necessary inconsistency.

### PR DESCRIPTION
**Pull request by LeeTibbert**
With respect to John Wesley sermon on cleanliness.

The order/disorder can be called either "obsessive compulsive" or "software engineering". 
Dealer's choice.

From the git commit:
Make C resources posix directory structure parallel scala structure. 

This pull request requires the prior acceptance of PRs #1257 and prior.

  * Inserted C files from the nativelib/src/main/resources into their
    proper place in the resources/posix sub-tree. 

    "Proper" is defined as being the place in the scala/scalanative/posix
    where the corresponding .scala file resides.  That is, make the
    two trees parallel.

    For example, resources/types.h becomes resources/posix/sys/types.h
    because:

      + The C file is used by only other posix C files.
      + The corresponding scala file is scalanative/posix/sys/types.h.

    The idea is to reduce the cognitive load for future contributors.

  * Created new resources/libc directory and moved file wrap.c there.
    This gives the fabled "developer in a hurry" of English common law
    a clue as to what wrap.c does.

    One might argue that a directory with one file does little to
    reduce the complexity of the top level resource directory. Such
    a position is understandable.  The current benefit of the new
    libc directory is that it gives future developers a clue as to
    how new files should be organized, particularly if they deal with
    libc. That is, cluster by concept in a directory.

    The same concept could be applied to unwind.c, and possibly other
    files.  I did not touch unwind.c because I expect it unlikely that
    there will ever be another file dealing with unwinding and I was
    running out of time.

64/32 bit issues:

      No known issues.

Documentation:

      No user facing documentation changes.

Testing:

	"sbt test-all" passes on a Linux 64 bit system. Not
	tested on 32 bit.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
3 out of 4 builds pass on Travis. Fourth appears to be Travis glitching. I know of
no easy way to restart Travis. "git commit --amend" puts me in git Hell.

**Comment by LeeTibbert** [comment]
Let me take this PR out of consideration for SN 0.3.8.  I can not get a clean merge, so I need to wait for #1257 to merge and some dust to settle.  I still think the idea is good. It is just that the implementation has not aged well.

**Comment by LeeTibbert** [comment]
Worthy idea, but the code tree has, for other worthy reasons,
seen substantial reorganization.

I may try again if I get time & motivation.

Close to keep the PR stream lean & relevant.

**Comment by ekrich** [comment]
Lee, I agree with this in principle but I think a better solution is to support `src/main/c` setup in the build. It would be nice to know if the code will compile early as well. https://github.com/scala-native/scala-native/issues/657

**Pull request closed without merging**
