### PR TITLE
Fix CLA validation

### PR DESCRIPTION
**Pull request by densh**
This is a WIP pr to debug travis/github interaction.

### CODE REVIEW

**Comment by densh** [comment]
It looks like github rate-limits unauthenticated API accesses per IP and it's failing because of that.

**Comment by densh** [comment]
I've added auth with dummy account to fix that. We can't even store the password securely as travis doesn't expose secure keys in pr validation.

**Comment by sjrd** [comment]
Er wait ... you've created a GitHub user with a password that is plainly exposed here? How is that not completely insecure? Can't you at least use an API key or something that doesn't actually leak *access to the account*?

**Comment by densh** [comment]
You either use [basic authentication with key+pass or go nuts with OAuth](https://developer.github.com/v3/auth/). There is no secure place we can use in travis to store the pass. And that's just a dummy account just for this purpose. It's not like it has access to anything at all. That's the only solution I see at the moment...

**Comment by DarkDimius** [comment]
I remember @xeno-by had a project on heroku that did pr-validation.
Maybe you can reuse some parts of it?

**Comment by densh** [comment]
@DarkDimius It was not worth it maintenance-wise, that's why @xeno-by migrated to pr validation script instead.

**Pull request merged**
