### PR TITLE
Jenkins setup

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by muxanick** [comment]
is it possible to add windows os later when it will be supported by Scala-Native?

**Comment by Duhemm** [comment]
@muxanick Of course! It should be as easy as adding a new Windows node to our Jenkins instance, and adding Windows to the `Jenkinsfile`.

**Comment by densh** [comment]
LGTM, thanks @Duhemm ! 👍

**Comment by Duhemm** [comment]
Woohoo! Let me know if I can still help with the Jenkins setup!

**Comment by densh** [comment]
And here is our first all-green, {linux, mac} x {gc=none, gc=immix, gc=boehm} build:

screen shot 2017-12-08 at 17 37 54

**Comment by ekrich** [comment]
Wow, 25 minutes, that is great!

**Pull request merged**
