### PR TITLE
Fix #1832: Justify existence and contents of build .sbtopts

### LINKED ISSUE #1832: Are Spring 2020 sbtopts reasonable?
I am having strong doubts that the `.sbtopts` introduced in Spring 2020 are reasonable.
Java memory management is a complex subject and I am not even a grasshopper but
I raise my doubts.  I believe that the present options are, in general, to large to begin with
and too limited on systems with plenty of memory.

For a number of weeks now, I have been running the options below on a modest 4 core Intel
system with 16GB RAM.  On that system, it starts with a lower heapsize but allows it to grow
about 1GB larger, if needed.   I have not taken the time to see what the heap usage is on
my system which mainly builds & exercises Scala Native.  

```
-J-XX:GCTimeRatio=29
-J-XX:+PrintCommandLineFlags
```
The `PrintCommandLineFlags` are just so I can see what sizes are being used, and which Java GC.
The 29 is set up to minimize garbage collection (by allowing more RAM to be used.)
Works for me.  

Of course, all of this memory management is Java 8 specific and changes with more current
Java and/or different garbage collectors.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This PR extends PR #1783.  That PR added the file .sbtopts to
    the project root. That .sbtopts contained hard coded values
    for memory settings to be passed to the Java Virtual Machine used by
    sbt.

    This PR makes it evident why the apparently useless and distracting
    .sbtopts is necessary and has the contents it does.

    The file itself seemed to be the place where the description
    is most likely to be found. This is to save someone else the
    the two or more weeks I have wasted chasing this issue.

    The short story is that after a fresh git clone interactive builds
    using the default scala-sbt.org sbt runner may fail because that
    runner sets the Java 8 MaxHeapSize variable too low. It sets that
    option to 1GB whilst the  "test-tools" and "test-all" Scala Native
    build.sbt commands need approximately 3GB.

    Travis CI succeeds because it explicitly sets the Java memory option
    and this explicit command line value overrides any previous value.

  * I welcome and encourage bike-shedding and suggestions for change
    for the wording of `.sbtopts`.  There are a number of intertwined
    non-obvious concepts and it is possible to go sliding down the
    rabbit hole quite quickly. All of this is going to change, so the
    challenge is getting a "clear enough" description that does not
    take hundreds of person-hours to create.

  * Nothing in this PR precludes a person or team from running with
    a local .sbtopts tuned to their (sic, 2020 use of 'their') system.
    In fact, that is exactly what I do, using the sbt-extras runner and
    the option "J-XX:GCTimeRatio=29". This give me about a 10% reduction
    in wall clock execution time.

  * For the curious, I ran experiments testing Travis CI. Increasing
    its MaxHeapSize resulted on no observable decrease in wall clock
    execution time.

Documentation:

  * The usual change note is requested.

Testing:

  * Built ("rebuild")and tested ("test-all") in debug mode using sbt 1.3.13
    & Java 8 on X86_64 only . All tests pass.

### CODE REVIEW

**Comment by ekrich** [comment]
@LeeTibbert I guess I am wondering why after all this time of not having `.sbtopts` that we need it now? Did `sbt` change the defaults in some more recent release?

What is the default `sbt` memory?

If the test runner is a spawned process, can't we influence the memory from inside `sbt`?

**Comment by LeeTibbert** [comment]
@ekrich Thank you for your questions.

Under the category of "Stuff I wish I did not know and want the time back
spent learning".

What I have discovered, much to my dismay, over the past several days, is that 
an adjustment to the Java MaxHeapSize is needed for __Interactive__  builds
using the prevalent scala-sbt.org sbt runner.    That runner caps the 
largest "-J-Xmx" at 1G, no matter how much more RAM is available
(must have made sense to someone.)   There is a "shadow" chain were
later values can override earlier ones.    So out-of-the-box, Travis CI Dockerfile
will work because it explicitly sets -J-Xmx to the equivalent of 3G when
it invokes sbt.

So the .sbtopts is needed to be civil/inviting to people doing fresh clones of
the Scala Native repository and attempting to build and run the tests.

**Comment by LeeTibbert** [comment]
> If the test runner is a spawned process, can't we influence the memory from inside sbt?

Over the years we have walked together through the murk & mire of the language of the
test environment.   Sbt's recursiveness is cute, but, at least for me, not worth the conceptual
complexity.  The term "runner" is used all over the place, meaning different things.

I did not figure out if the memory requirement came from the SBT jvm runner code or from
the the SN binary image runner.  Given the choice of tolerating a well-commented .sbtopts
or diving into setting process options on the SN binary, I would chose the former.  

I can run an experiment to see which "side" is actually doing the complaining. I think it is
Scala itself trying to compile the unit-test code.   That piece of information would help
us make a better data-driven decision.

**Comment by ekrich** [comment]
Thanks for answering. Just seems hard to believe that we have been using this and maybe suffering because of defaults.

**Comment by LeeTibbert** [comment]
To clarify & ground the discussion, the problem come when Scala Native is creating the SN binary.
From the stacktrace, it looks like a clever & motivated person could change the memory of the
forked optimization process, but I doubt that work would pay back the time & expertise required.

At least now, the requirement is documented, and easy to change/tune.

@ekrich Your thoughts?

For the purposes of this note, I was not able to provoke test-tools to fail with 1GB memory.
I may have encountered that in a Travis CI log with different RAM amounts.

$ ~/Scratch/Scala-sbt_org/sbt/bin/sbt -v    -J-XX:+PrintCommandLineFlags "test-all"
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options=()
# Executing command line:
java
-Dfile.encoding=UTF-8
-XX:+PrintCommandLineFlags
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
<redacted>/Scala-sbt_org/sbt/bin/sbt-launch.jar
test-all

XX:InitialHeapSize=1073741824 -XX:MaxHeapSize=1073741824 -XX:+PrintCommandLineFlags -XX:ReservedCodeCacheSize=134217728 -XX:ThreadStackSize=4096 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC 
[info] welcome to sbt 1.3.13 (Private Build Java 1.8.0_252)
# many lines deleted
# Beginning tests/test section
info] Linking (5906 ms)
[info] Checking intermediate code (2443 ms)
[info] Dumping intermediate code (linked) (3439 ms)
[info] Discovered 6370 classes and 33625 methods
[info] Optimizing (debug mode) (18266 ms)
[info] Checking intermediate code (785 ms)
[info] Dumping intermediate code (optimized) (11290 ms)
[error] java.lang.IllegalArgumentException: Self-suppression not permitted
[error]         at java.lang.Throwable.addSuppressed(Throwable.java:1072)
[error]         at scala.collection.parallel.Task.mergeThrowables(Tasks.scala:74)
[error]         at scala.collection.parallel.Task.mergeThrowables$(Tasks.scala:72)
[error]         at scala.collection.parallel.ParIterableLike$Map.mergeThrowables(ParIterableLike.scala:1053)
[error]         at scala.collection.parallel.Task.tryMerge(Tasks.scala:69)
[error]         at scala.collection.parallel.Task.tryMerge$(Tasks.scala:66)
[error]         at scala.collection.parallel.ParIterableLike$Map.tryMerge(ParIterableLike.scala:1053)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:177)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
[error]         at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
[error]         at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error]         at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error]         at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error]         at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error]         at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error]         at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
[error]         at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
[error]         at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
[error]         at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:960)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error]         at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:955)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] (tests / Test / nativeLink) java.lang.IllegalArgumentException: Self-suppression not permitted

**Comment by LeeTibbert** [comment]
Agreed, the situation has probably been a put-off for new users for a while.  The good news is that one of them,
kerr @hepin1989 took the time to fix it. That encourages me.

**Comment by LeeTibbert** [comment]
> `error] (tests / Test / nativeLink) java.lang.IllegalArgumentException: Self-suppression not permitted`

That error is more than a bit out of place, but I am not going to go haring off after it.

**Comment by ekrich** [comment]
From the latest post on the `sbt` Gitter - https://gitter.im/sbt/sbt?at=5f0dcc8549fe212794948dfe
https://stackoverflow.com/questions/3868863/how-to-specify-jvm-maximum-heap-size-xmx-for-running-an-application-with-run/14561346

**Comment by LeeTibbert** [comment]
Yes the python "There should be one, and preferably only one, way to do something" principle
seems to be conspicuously absent.  Sorta like frequently irregular verbs in English and other
languages.   Both `.sbtopts` and `.jvmopts` work and appear to overlap.  Because I never use it,
I am not sure if the scala-sbt.org runner differs in how they are processed (and which has effective precedence).

I had thought of renaming the `.sbtopt` file from the prior PR to `.jvmopt` but decided against it, to reduce
churn without a payback.   I figure any poor damned soul chasing those two would have to know enough
about sbt and the specific runner in use to figure out that both could be used and when.

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
