### PR TITLE
Fix a few typos in javalib 

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fixed a few typos.

### CODE REVIEW

**Comment by densh** [comment]
@eatkins Does thing change looks good to you?

**Comment by eatkins** [comment]
LGTM except that I think the merge commit should be removed.

**Comment by eatkins** [comment]
I'd run the following:
```
git fetch origin
git rebase -i origin/master
```
The interactive rebase gives you the option to edit or remove commits. You can just delete the merge commit at the top of your editor. When that's done, re-push the branch with `git push -f $YOUR_GITHUB_FORK $BRANCH_NAME`.

**Comment by eatkins** [comment]
BTW, no need to apologize. We are all beginners at something.

**Comment by LeeTibbert** [comment]
@eatkins  Thank you for the information &, especially, the encouragement.

I thrashed around for a few hours, no kidding!, and got this PR down to 1 commit with the two files I wanted to change. Almost certainly more 'blind squirrel' than skill or understanding.

 I believe the PR is clean.

**Comment by densh** [comment]
LGTM, thanks @LeeTibbert, @eatkins ! 👍

**Pull request merged**
