### PR TITLE
Performance improvement: Immix GC: Concurrent sweep

### PR DESCRIPTION
**Pull request by valdisxp1**
Based upon #1378
## Features:
- New `SCALANATIVE_GC` option  `commix` to enable the new GC changes.
- Concurrent sweep. Reduced GC pause times by utilizing additional processor cores during sweeping.
- Configurable number of GC threads with `SCALANATIVE_GC_THREADS` environment variable. Set to number of available processors - 2 up to 8, but no less than 1.
- Lazy sweep when setting `SCALANATIVE_GC_THREADS=0`.
- Stats changed to event-based CSV format.
- Stats now also saves events for collection start and end.
- Stats includes `start_ns` column - time in nanoseconds since application was started.
- Stats is compatible with the new concurrent sweep events.
- Increasing heap size until mark is <=5% of total time. 
## Internals:
- thread-safe `BlockList`s
- thread-safe `BlockRange`s
- thread-safe block counts
- new block flags in `BlockMeta`
## Debugging :
- asserts in Immix can now be enabled by setting `DEBUG_ASSERT` flag
```scala
nativeCompileOptions += "-DDEBUG_ASSERT"
```
This similar to the way you could enable trace level printing and debug symbols.
```scala
// trace level printing in Immix
nativeCompileOptions += "-DDEBUG_PRINT"
// enable debug symbols for C code
nativeCompileOptions += "-g"
```
- More integrity check asserts for sweeping.
## Refactoring:
- Moved `Block_Sweep` to `Allocator_Sweep` in order to match `LargeAllocator_Sweep`.
- Tenamed `block_superblock_middle` to ` block_superblock_tail` in order to avoid confusion. This block flag is used for both middle and last blocks.

On Intel i5-3470:
Reduces GC time on the main thread by 47.65% (geomean) on default heap size and by 97.04%(geomean) on 1GB heap.

https://github.com/valdisxp1/scala-native-benchmark-results/blob/intel-i53470/reports/summary_20190109_110202_scala-native-0.3.9-SNAPSHOT%40master-concurrent-base%40origin-gc_vs_scala-native-0.3.9-SNAPSHOT-commix%40concurrent-sweep-timed-growth%40origin-gc/Readme.md#total-gc-time-on-application-thread-ms
https://github.com/valdisxp1/scala-native-benchmark-results/blob/intel-i53470/reports/summary_20190109_105818_scala-native-0.3.9-SNAPSHOT%40master-concurrent-base%40origin-gc_size_1g-1g_vs_scala-native-0.3.9-SNAPSHOT-commix%40concurrent-sweep-timed-growth%40origin-gc_size_1g-1g/Readme.md#total-gc-time-on-application-thread-ms
I switched off the GC metrics to eliminate their overhead and get more accurate performance measurements. For the default size we gain 2.21% performance (geomean at 50 percentile). On 1GB heap we improve the performance by 0.91 (geomean at 50 percentile) mainly due to the `List` benchmark.

https://github.com/valdisxp1/scala-native-benchmark-results/blob/intel-i53470/reports/summary_20190109_104803_scala-native-0.3.9-SNAPSHOT%40master-concurrent-base%40origin_vs_scala-native-0.3.9-SNAPSHOT-commix%40concurrent-sweep-timed-growth%40origin/Readme.md
https://github.com/valdisxp1/scala-native-benchmark-results/blob/intel-i53470/reports/summary_20190109_105818_scala-native-0.3.9-SNAPSHOT%40master-concurrent-base%40origin-gc_size_1g-1g_vs_scala-native-0.3.9-SNAPSHOT-commix%40concurrent-sweep-timed-growth%40origin-gc_size_1g-1g/Readme.md#total-gc-time-on-application-thread-ms

__Updated January 9 2019__

### CODE REVIEW

**Comment by rwhaling** [comment]
This is really exciting work - can't wait to see the benchmarks!

**Comment by valdisxp1** [comment]
I got better performance after further cache locality optimizations. See new results in the description.

**Comment by rwhaling** [comment]
Just a thought - is there any way we could get a build-time flag to force the `SCALANATIVE_GC_THREADS=0` behavior?  Certain kinds of programs, especially ones using fork(), might rely on lazy, single-threaded GC for correct operation.  Maybe something like: `nativeGC := lazyImmix` or something like that?

**Comment by ekrich** [comment]
@rwhaling Could you expand on what you are thinking, how the GC is going to interfere with the application on the whole?

**Comment by valdisxp1** [comment]
Working on improving the performance with more than two CPU cores. In the mean time I got a stable implementation of parallel marking. I am combining both under #1423 .

**Pull request closed without merging**
