### PR TITLE
add null checks for Throwables

### PR DESCRIPTION
**Pull request by musabilal**

### CODE REVIEW

**Comment by densh** [comment]
Hi @musabilal. Thanks for the contribution! Please sign [Scala CLA](https://travis-ci.org/scala-native/scala-native/jobs/182863399#L385) so that we can proceed with this PR.

**Comment by musabilal** [comment]
Hi @densh I have signed the Scala CLA now, do I need to resubmit the pull request?

**Comment by densh** [comment]
No need to resubmit, I've just restarted the CI.

**Comment by densh** [comment]
This PR needs some love from `bin/scalafmt`.

**Comment by densh** [comment]
Also needs `// Ported from Scala.js.` comment as discussed in https://github.com/scala-native/scala-native/pull/431#discussion_r91926193.

**Comment by musabilal** [comment]
I have

- run bin/scalafmt for the added code
- added comment "// Ported from Scala.js." to the commit

**Comment by densh** [comment]
LGTM, thanks!

**Comment by MasseGuillaume** [comment]
@musabilal congrats!

**Comment by musabilal** [comment]
@MasseGuillaume thanks for all your help!

**Pull request merged**
