### PR TITLE
Bump to sbt 1.2.1 for travis ci

### PR DESCRIPTION
**Pull request by densh**

### CODE REVIEW

**Comment by densh** [comment]
It still looks like sbt 1.x build is 4-6 minutes slower than 0.13.x.

**Comment by jonas** [comment]
Based on how many CI runs?

**Comment by densh** [comment]
@jonas It's not meant to be a rigourous performance evaluation, I did a few restarts, 1.x seems to be consistently slower (usually 4+ more minutes than 0.13.16). I suspect that the difference comes from scripted tests which start a new sbt instance on every test suite which amplifies cold start performance degradation in 1.x.

**Comment by jonas** [comment]
Okay, there was some work planned by Scala Center to make scripted tests faster. I don't know if it got done.

**Comment by ekrich** [comment]
It looks like there may be a workaround - https://gitter.im/sbt/sbt-contrib?at=5b7c5f5258a3797aa398ebc6

**Comment by densh** [comment]
@ekrich We don't publish from scripted, so that shouldn't affect us.

**Pull request merged**
