### PR TITLE
Profiling

### PR DESCRIPTION
**Pull request by Duhemm**
Continuation of #447.

To continue the discussion:

> Do you still keep the whole profile in memory and dump it in the very end of execution?

Yes.

> Have you considered writing to disk in batches?

Yes, but my primary concern was the size of the output rather than the memory consumption. Is it okay to write a several-GBs-long profile?

### CODE REVIEW

**Comment by densh** [comment]
How well do profiles compress with zip?

**Comment by Duhemm** [comment]
Extremely well. The profile for `richards` goes from 6.5MB to 83KB. Are you thinking about compressing and writing all the batches independently, or did you have something else in mind?

**Comment by densh** [comment]
We can try recording profiles in in-memory up until some size (e.g. 4MB), as soon as batch is full we compress it with zlib and dump it to file `myprofile.1` and then the same procedure repeats to generate `myprofile.2` and so on and so forth. Profile reader then takes a sequence of files and processes them in order to extract the information it needs.

**Comment by Duhemm** [comment]
I changed the code so that we write and compress 4MB chunks. This way, we can collect a profile for the benchmarks.

Running a single iteration of every benchmark generates a profile of 210MB (8,055,051,048 events). Reading the full profile takes 311,421ms (~25,861 events/ms).

**Comment by densh** [comment]
I think this is a fantastic result in terms of size! I am merging keeping this as `topic/event-profiling` as we need to play with it a bit longer before we merge it to master, especially considering imminent 0.1 release. Thanks @Duhemm ! 🍰 ✨

**Pull request closed without merging**
