### PR TITLE
Fix #195: ABI of extern functions receiving structs as params differs from clang's

### LINKED ISSUE #195: ABI of extern functions receiving structs as params differs from clang's
```c
struct Foo {
    int bar;
    int baz;
    int next;
};
extern void consumeFoo(struct Foo foo) {
    printf("consuming foo: %d %d %d\n", foo.bar, foo.baz, foo.next);
}
```
```scala
@struct
class Foo(val bar: CInt, val baz: CInt, val next: CInt)
@extern
object C {
  def consumeFoo(foo: Foo): Unit = extern
}
object Main {

  def main(args: Array[String]): Unit = {
    C.consumeFoo(new Foo(1, 2, 3))
  }
}
```
this results in "consuming foo: 1 0 2" printed, instead of expected 1 2 3

### PR DESCRIPTION
**Pull request by Yoitsumi**

### CODE REVIEW

**Comment by Yoitsumi** [comment]
So it seems, like big structs (>16 bytes) aren't actually passed by reference, but on stack. In clang it's solved by a byval attribute to an argument like here:
`define i32 @visit(%struct.CXCursor* byval align 8 %cursor, %struct.CXCursor* byval align 8 %parent, i8* %cd) ...`
I believe, that the best solution would be to add a new type, `ByvalPtr(ty: Type)` just for these functions, what do you think, @densh ?

**Comment by Yoitsumi** [comment]
Unfortunately no, adding a new type doesn't seem to be a good idea. We would have to show it in llvm ir as `"$ty* byval"`, but byval is only allowed in function declaration or call. It should probably be encoded somehow in the function type (attrs?), but i'm pretty sure, that we need these parameters to be actual *typed* pointers (not just `i8*`), since llvm needs to know how much space to allocate on the stack.
I'm stuck, i have no idea how this should be solved.

**Comment by densh** [comment]
If we add byval it should be an attribute on the argument of a function type as that information is needed both for the definition of the function and for the call instruction that is used to call it. Currently we did not need any of those yet, but this seems to be about time to add them.

**Comment by densh** [comment]
@Yoitsumi The solution for untyped pointer problem is to make NIR version of byval to take a type parameter. This type can then be used in llvm code gen to emit proper pointer type. Pointer types are untyped on purpose as that's the direction where LLVM is headed (but it hasn't happened yet.)

**Comment by densh** [comment]
Sorry for the delay on the review, more feedback to come once I get back from Italy after July 25.

**Comment by Yoitsumi** [comment]
I tried adding byval argument attribute, but now demoNative overflows the stack, which is weird, since i don't think i introduced any more alloca's.
Also, sorry, that this is taking so long, i've been a bit busy with work lately.

**Comment by densh** [comment]
@Yoitsumi Thanks a lot for research & development on this issue! I've been also busy with fixing other issues, this progress wouldn't be possible without your efforts.

**Comment by Yoitsumi** [comment]
The good news is, the abi issue seems to be fixed, i was able to call clang apis using structs and get all functions declared in a .h file. The problem is, that demoNative now runs quite a bit slower and overflows the stack (i had to increase stack space limit for it to complete successfully). The slowdown is probably due to all the structs passed as arguments having to be stored somewhere on the stack before being passed. I think the best solution here would be to only apply the abi changes to extern functions and function pointers and revert to the original behavior with internal functions. I've started implementing this, but i'm not sure how to get the information about called function (whether it's extern or not) in a compiler pass. @densh do you have any pointers for me?

**Comment by Yoitsumi** [comment]
Extracted part of the changes to #299, will continue work on this issue after that gets merged.

**Pull request closed without merging**
