### PR TITLE
set array length after memory allocation

### PR DESCRIPTION
**Pull request by fbertra**
``
  (new Array [T] (len)).length ()
``

always return zero because the length of the requested array isn't stored.

### CODE REVIEW

**Comment by fbertra** [comment]
A app to test this pull request

https://github.com/fbertra/scala-native-test_set_array_length

Note: I didn't find where to put tests inside the scala-native project.

**Comment by densh** [comment]
Hi @fbertra, thanks for fixing the issue. The arrays are currently implemented textual templating that is expanded through `project/gyb.py` script. Please update the `Arrays.scala.gyb` and re-generate the source. We currently don't have a test suite yet unfortunately but it's on the near-future roadmap https://github.com/scala-native/scala-native/issues/28

**Comment by fbertra** [comment]
@densh, done.

The preprocessor was at plain sight, I can't believe I didn't seen it.

**Comment by densh** [comment]
LGTM, thanks for the contribution! 🍰

**Pull request merged**
