### PR TITLE
Update fmt to 3.7.14

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:

3.7.14 can be used with `scala-cli fmt`, which is fast.

Will submit another following pr for ignore this commit once this get merged.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Kerr,

Congratulation on your success!  Only eight files changed, I am pleasantly surprised.
I had expected a hundred or so. Shows what I know.

Looks like the CI failures of this PR are all in multiarch, sorry.  PR #3485 should fix that,
once merged.

**Comment by He-Pin** [comment]
> Kerr,
> 
> Congratulation on your success!  Only eight files changed, I am pleasantly surprised.
> I had expected a hundred or so. Shows what I know.
> 
> Looks like the CI failures of this PR are all in multiarch, sorry.  PR #3485 should fix that,
> once merged.

One should try first😊😊😊

**Comment by ekrich** [comment]
Good job on this one. The changes were to fix an issue and was introduced in 3.7.0 - https://github.com/ekrich/sconfig/pull/292/files

You can do a `.git-blame-ignore-revs` like the above commit and we could probably add one for the other big format changes too if people want to.

**Comment by He-Pin** [comment]
@ekrich this will be merged with squashed? or i added it in this pr and we merge it without squashing

**Review by ekrich — APPROVED** [review]
LTGM. Thank-you for this contribution.

**Comment by He-Pin** [comment]
@ekrich I will rebase my another ontop of this:)

**Pull request merged**
