### PR TITLE
[WIP]  Move towards consistent scala & C type definitions and more complete posix

### PR DESCRIPTION
**Pull request by LeeTibbert**
PR #1252  punted converting stat.scala and unistd.scala to DRY foundational
datatypes because the conversion was too complex.  This PR addresses
those files, pro peccatis meis.

From the commit message:

Move towards consistent scala & C type definitions and more complete posix.

This pull request requires the prior acceptance of PRs #1243, & #1252.

  * Alphabetized in many places to ease checking things that should match
    actually do.  This is software engineering, not code churn.

  * Tuned types.scala and types.h for _LP64 & __ILP32__ data models. That
    is, 32 bit integers on both 32 & 64 bit hardware with longs and pointer
    sizes matching  architecture bit count.  Added code to top of each
    to indicate the other should match or, at least, be consistent.

    Someday one file will be generated from the other but this is the
    best that can be done now to ensure the two points of truth match.

  * Modified stat.scala and unistd.scala to declare and use the
    foundational types in types.scala. The type declarations
    in stat.scala and unistd.scala are a move towards better compliance.

  * Populated stat.scala and unistd.scala with more, but not all,
    posix declarations. Added supporting code to stat.c and unistd.c.

    Removed many simple scalanative @name declarations and corresponding
    C code. This to make it easier to tell when the scalanative C layer is
    actually doing a transform and reduces both source and generated code
    sizes.  Other files could probably benefit from this change.

  * Added the AT_* types to fcntl.scala and fcntl.c. These are n
    needed by newly declared unistd.scala linkat().

  * A changing to unistd.scala read() to the posix definition revealed
    an issue on 64 bit systems in javalib FileInputStream.scala.
    On those systems unistd read() can return 64 bits while java
    can only handle 32 bits. Type checking revealed the mismatch, yeah!
    The truncation (.toInt) now in that file is safe. The length argument
    passed to unistd.read is an Int argument to the enclosing function
    so unistd.read will return a long, but the value in that long
    will always fit into an int.

64/32 bit issues:

      types.scala definitions are tuned to work on 64 bit systems
      and 32 bit X86 systems.

      In particular, I have _NOT_ tested on ARM. There is robustness code
      in resources types.h to FAIL the compilation on untested 32 bit
      systems.
Documentation:

      No user facing documentation changes.

Testing:

	"sbt test-all" passes on Linux 64 bit systems & 32 bit X86.
	I was not able to test on OSX or other operating systems or
	hardware.

### CODE REVIEW

**Comment by ekrich** [comment]
For “scalanative_o_at_eaccess”, do you need the ‘_o_’ for AT_EACCESS?

**Comment by LeeTibbert** [comment]
@ekrich  Good eyes, good catch!  Thank you for the review.
I am surprised and disappointed that the code passed CI testing, sigh!

Fixed in PR#1259 because that PR changes fcntl.* after this one.
I am hoping that editing the later PR eases the merging of this PR series.

I changed names to "scalanative_fcntl_at_*" in an attempt to name-space,

**Comment by ekrich** [comment]
@LeeTibbert I believe that C is a flat namespace so you can just use `scalanative_<macro_or_function_name>`. I also noted that most POSIX headers include declarations that are also in `sys/types.h`. See http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html
```
The <time.h> header shall define the clock_t, size_t, time_t, types as described in <sys/types.h>.
```
I think we should also standardize on uppercase for those that are uppercase in C. e.g. 
```
scalanative_AT_EACCESS
```

**Comment by LeeTibbert** [comment]
@ekrich 

Thank you for your review & discussion. I appreciate both.  You make three points, so let me quote and address them in separate comments, the better to associate comment and reply.

**Comment by LeeTibbert** [comment]
`@LeeTibbert I believe that C is a flat namespace so you can just use scalanative_<macro_or_function_name>`

Agreed, the C namespace is  flat but I am proposing with the scalanative_fcntl_* naming in this PR
that the scalanative side of declarations follow the scala practice of having a somewhat segmented namespace, if only by convention.  As I was working on this PR, I found that I was being made more crazy than I usually am by trying to figure out in which C (consequently, .scala) file a symbol such as
AT_FOO was being declared.  I found having the `@name` contain the filename, e.g. "scalanative_fcntl_at_foo" helped me stay oriented.

Posix grew by accretion & experience. It is better than what came before it, but I find it a 
_mighty_ tangle.

If you, @denesh, or somebody senior want me to change the naming, either before or after 0.3.8, I am willing to do so.  Please advise.  L.

**Comment by LeeTibbert** [comment]
`I think we should also standardize on uppercase for those that are uppercase in C. 
e.g. scalanative_AT_EACCESS`

I like the idea but here might be a problem in C land.

There might be some special compiler and or linker flags to allow mixed
case symbols but to a first approximation and to most of the world C is
case blind.  

The C convention I learned is that uppercase implied a macro definition. 
These days that might extend to a `const`. Times change.

I believe the C files will convert a function name scalanative_AT_EACCESS to 
scalanative_at_eaccess  and would be willing to change the names, again either before or
after 0.3.8.  I'd prefer not to touch C or linker flags; my life is short, Summer is short, and life is good.

The question of when to follow prior art in a file and when to break it is always a question of wisdom, especially on a maturing file.  I spent _quite_ a bit of time trying to figure out the convention/consistency/prior_art and then following it to the best of my understanding.

It seemed to me that in unistd.scala one has, from well before I ever touched it:
```
 @name("scalanative_f_ok")
+  def F_OK: CInt = extern
```
The scala name is the same as one would see in C code. That is good, by my thinking.
The scalanative* name is all lowercase, probably for the reason I mentioned above.

Now, I have this all wrong, I await marching orders, or at least marching suggestions.

L.

**Comment by ekrich** [comment]
@LeeTibbert I not sure what I was thinking but I agree with this format.
```
@name("scalanative_f_ok")
+  def F_OK: CInt = extern
```

**Comment by LeeTibbert** [comment]
Updated javalib nio Files.scala so that it compiles with the stricter type definitions in unistd.scala provided by this PR.  No functional change.  

Builds & passes test-all on my 64 bit system. Awaiting Travis CI results.

I will create two issues for 'features' I found whilst editing Files.scala readAllBytes.

**Comment by LeeTibbert** [comment]
Corrected.  Conflicting with my own prior edits!  I do not know how I managed that.

4/4 Green. Travis is having a good day, which means that I am having a good day (so far)!

I hope this one merges smoothly & sorry for the trouble.

**Comment by LeeTibbert** [comment]
Update: 2019-07-16

I am keeping this PR open because I am gradually picking its bones for current PRs.
PR #1621 addresses unistd.scala   

There are several PRs against fcntl.scala. I hope fold the changes from here into
a fresh PR for fcntl.scala once those PRs have been accepted.

I believe that many of the changes to types.scala from here have already been 
folded into PRs on that file.

**Comment by LeeTibbert** [comment]
Good core idea but overcome by there passage of time.
The need will loop around again and appear.

Clear the decks for currently active PRs.

**Pull request closed without merging**
