### PR TITLE
Fix #2943: Provide smarter & faster ProcessTest method

### LINKED ISSUE #2943: j.l.ProcessTest#processForDestruction() should be smarter & faster
javalib ProcessTest method `processForDestruction()` was implemented in the middle of
the night to deal with a specific pain point in CI.  The goal at that time was correctness, not
necessarily an elegant implementation.

`processForDestruction()` was implemented to have a fixed 10 second Thread.sleep().
It gets called twice per ProcessTest run, so that is 20 seconds of wall clock time gone.
Especially annoying if one is sitting at a terminal monitoring unit-tests. Expensive
over the many (hundreds?) of times ProcessTest can be run in CI in a day.
Everybody loves faster CI ensembles, especially when they complete in less
than a week.

Instead of waiting for a fixed amount of time, when the process is almost
certainly ready in a tenth of that time, `processForDestruction()` can wait and
read the first byte of output from the child.  If the child can produce output,
it is past its formative "exec" call and ready to receive SIGTERM or SIGKILL.
Pretty creepy when you think about it.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #2943

A fixed delay in ProcessTest is avoided.

In my private tests, the time for the two affected tests went down from a quite noticeable 10+ second pause
to an almost unnoticeable 2 or fewer seconds.  

Multiply that by the number of times the test is executed per CI run times the number of CI runs
per day and the wall clock savings begins to add up.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Could this CI run please be restarted?   Thank you.

As I end this sprint, the multi-arch tests are failing for reasons outside this PR.
I need to see at least one of the "test-runtime" instances succeed so that I 
know that environment has the "ping" command used in this PR.
It _should_ because multi-arch runs on Ubuntu, which ships with it,
but I need to see with my own eyes.

**Comment by WojciechMazur** [comment]
Multiarch would be fixed soon in #2939. I took a while but it should be finally stable. For some reason building of Boehm GC for x86 has started to fail recently and I was not able to fix it easily.

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
@WojciechMazur  Thank you for your dedication & effort keeping the build going.

**Comment by LeeTibbert** [comment]
@WojciechMazur    

Sorry, this PR introduced breakage into the multi-arch build. 
The one you worked so hard on.

There are at least two possible solutions.

1) Add package `iputils-ping Tools to test the reachability of network hosts` to each of the architectures.
    Since this is Ubuntu, I am surprised, but not astonished, that the package is not already installed.
   
    I can take a run at this in another PR. I also understand if you do not want other people tinkering
    with your finely tuned multi-arch build.

2) I could branch on Architecture and fall back to the previous "fixed" delay on the multi-arch 
    runs.  I would keep the "fast-path" for Linux, BSD, Windows, etc.

**Comment by WojciechMazur** [comment]
Hey @LeeTibbert I've opened the PR #2945 which would install the iputils-ping. Thanks for help if finding the solution. I belive the we should stick to your last improvement and adjust the testing environment instead of using the older approach.

**Comment by LeeTibbert** [comment]
Wojciech Thank you for PR #2945.

**Pull request merged**
