### PR TITLE
Update & supersede PR #1609: Implement java.nio UserPrincipal infrastructure.

### PR DESCRIPTION
**Pull request by LeeTibbert**
##### Intellectual Property Statement:

This PR is an update of original code in PR #1609 by
Claudio Bley (at_avdv) and is used by his kind permission
(see Issue #2128).

##### Commit message
We expand javalib by implementing UserPrincipal infrastructure.
In particular, this allows to lookup UserPricipals by numeric ids.

### CODE REVIEW

**Comment by ekrich** [comment]
I think it is a good practice to use the following and a prefix for any Java collections to make sure to avoid using Scala collections in the Java library
```scala
import java.{util => ju}

val map = new ju.HashMap
```

**Comment by LeeTibbert** [comment]
@ekrich Thank you for the review, catch & suggestion. Implemented.

**Comment by LeeTibbert** [comment]
Claudio (@avdv)  to give a clean Intellectual Property audit trail, could you take
a moment to confirm (or reject) the use of your original code here? Thank you.

You will notice that the ContinuousIntgration-only code that you and I worked 
on so long ago is not in this PR.  Feedback in PR #2241 directs against such tests.

The underlying code should look familiar, although, as we have discussed in passing,
I did move some file locations.

If you would like me to make any changes or if I have messed something up, please
let me know.

Hopefully, this PR will get merged and save you time and energy wondering
what broke or went missing when SN 0.4.next is released.

**Comment by avdv** [comment]
Hey Lee (@LeeTibbert),

good to see some progress on this one. :+1: I'll take a look when I find some time today...

**Comment by avdv** [comment]
> Claudio (@avdv)  to give a clean Intellectual Property audit trail, could you take
> a moment to confirm (or reject) the use of your original code here? Thank you.
> 
> You will notice that the ContinuousIntgration-only code that you and I worked 
> on so long ago is not in this PR.  Feedback in PR #2241 directs against such tests.
> 
> The underlying code should look familiar, although, as we have discussed in passing,
> I did move some file locations.

Yes, confirming that this is based on my original code. Thanks again!

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
