### PR TITLE
Improve `run/java-io-file` scripted test

### PR DESCRIPTION
**Pull request by Duhemm**
- Sort the files in the test for `File.list()` to avoid failures due to different orderings
- Split the scripted tests `run/java-io-file` to avoid issues with Travis CI.

@Korf74 Can you confirm this fixes the issue you encountered? I can't reproduce it on my machine.

### CODE REVIEW

**Comment by densh** [comment]
Needs a version bump to `0.3.0-SNAPSHOT` in https://github.com/scala-native/scala-native/blob/master/nir/src/main/scala/scala/scalanative/nir/Versions.scala#L28

**Comment by Korf74** [comment]
@Duhemm seems to work when I fork your branch on my computer

**Comment by Duhemm** [comment]
@densh I added the version bump as first commit. Github shows them in the wrong order: https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/

**Comment by densh** [comment]
@Duhemm please rebase on top of latest master.

**Comment by Duhemm** [comment]
@densh Done

**Pull request merged**
