### PR TITLE
Add script to format C/C++ code

### PR DESCRIPTION
**Pull request by jonas**
It uses the provided LLVM style.

### CODE REVIEW

**Comment by densh** [comment]
I second @ekrich suggestion, lets make it 4 spaces, 2 spaces looks really weird on C code.

**Comment by jonas** [comment]
@ekrich I missed that the indentation level should be 4. Thanks for the hint. Corrected.

**Comment by jonas** [comment]
Looks like this is actually a hard problem due to incompatibilities between how different versions of clang-format parses the configuration file.

**Comment by ekrich** [comment]
Can't we require a `clang-format` version greater than a certain number?

**Comment by jonas** [comment]
@densh Are you OK with making `clangfmt` require a specific Clang version? This would mean that developers either would have to have that version installed, which is straightforward on most systems or else we can do the formatting occasionally.

**Comment by densh** [comment]
@jonas I think it's perfectly fine to agree on a single version of clang-format to be used for development. This approach has been working nicely for scalafmt so far.

**Comment by densh** [comment]
Hey @jonas, I've tried the script and it works like a charm. What do you think would be the best version we should agree upon for this? 

This also needs a rebase on top of master due to conflicting changes in nativelib.

**Comment by ekrich** [comment]
Will this be as simple as the developer running the following at the command line?
`clang-format -i -style="{BasedOnStyle: llvm, IndentWidth: 4}" <file>.c`
Maybe we can put this in the developer section of the docs along with the following:
`scalafmt -i -f <file>.scala`
Maybe this can be added here. http://www.scala-native.org/en/latest/contrib/contributing.html#coding-style

**Comment by jonas** [comment]
@densh I suggest to choose the most recent version of LLVM that Scala Native officially support and make sure that version is used on Travis.

@ekrich Yes, I'll update the documentation to mention how to format C/C++ code.

**Comment by densh** [comment]
@jonas Sounds good to me, lets do that! 👍

**Comment by jonas** [comment]
@densh OK, ready for review then

**Pull request merged**
