### PR TITLE
Make list of supported classes prettier & easier to read and visually search

### PR DESCRIPTION
**Pull request by LeeTibbert**
Re-organize the presentation of the list of supported classes to make it easier to read and
visually search.  Beauty is in the eye of the beholder.

The list of supported classes was compared with the Java 8 API and "leaky" classes removed.
Someday the corresponding code should be fixed.

### CODE REVIEW

**Comment by ekrich** [comment]
No change to https://github.com/scala-native/scala-native/blob/main/scripts/javalib.py ?

This is part of the reason that I think we should just publish javadoc and point to it - nothing to maintain.

**Comment by LeeTibbert** [comment]
I should probably remove/delete `scripts/javalib.py` so that it does not clobber
what I have just done.  It is not like we are doing bulk additions to javalib 
these days, or are likely to be doing so in the foreseeable future.
I also do not see anyone on the horizon to fix `scripts/javalib.py` so that
is aware of packages.

**Comment by LeeTibbert** [comment]
Can GitHub retrieve a deleted file?  Is there a better way of archiving it than straight out
deleting it?  Say add some text & an early exit statement to the top of `scripts/javalib.py`
and rename it to `scripts/Archived/javalib.py.ARCHIVED`.    Not trying to make things
too complex, just acceding to he view that it may someday be a useful in the future.
How much clutter and misdirection do we want to keep around?

**Comment by ekrich** [comment]
I thought that script was run but if we are not using it we should probably remove it. I like the format but maybe the script can be updated to auto-generate in the new format.

@WojciechMazur Have you been using this script? 

What do you think about just generating the javalib scaladoc and then linking to it? We could document differences like exception messages and the like so it could be better than just empty scaladoc for the sake of the list of implemented classes. Either way it would be easier than maintaining the scripts or hand changing the list which is liable to get out of date or out of sync.

**Comment by LeeTibbert** [comment]
Eric,

I am pleased & encouraged that you like the new layout.

I propose that we keep this effort small, with the potential
for getting to "Done".  I'll wait for input from Wojciech before I make
any changes.    

I think deleting `scripts/javalib.py`  is on any branch forward.

The major concern that I have with relying on scaladoc generation
of the javalib class coverage information we present to users is
that I do not remember there being much scaladoc in javalib;
not even class names.  It may be there and my eyes and memory
skip over it or lack understanding/appreciation.

From my recent work, I know that there are some classes declared
within classes, the Foo.foo in the manual list (used to be the
misdirecting "Foo$foo", the .py script generated close but wrong
names).  Can scaladoc handle that, or would that be a manual pass?

Given a  hundred hours of developer effort,  I'd rather put it into
either making clib & posixib more complete or in ensuring that
the scaladoc for those was reasonable.  I think those are problems
solvable in economic time.  Then again, we have to come up with the hypothetical
hundred hours of  developer time in the first place.

**Comment by ekrich** [comment]
Generating `scaladoc` for the `javalib` would generate all public and protected classes and methods so it would be correct like `javadoc` we use - if things are in the `javalib` that are public/protected but not part of the Java specification then they would need a `scaladoc` comment saying they are an implementation detail. This could also help internal developers.

You can see here for `posixlib` that all the packages, classes, and methods are generated regardless of whether there is `scaladoc` comments. https://javadoc.io/doc/org.scala-native/posixlib_native0.4_3/latest/index.html

**Comment by WojciechMazur** [comment]
I think I did used it once in the past, but it's definitely not very usable and required manual fixes to generated output - especially filtering implementation-specific classes. It also was designed for usage with Scala 2.11,so when working with lastest releases it introduces some unexpected classes. 
I think we can remove it, and try to fix the scaladoc generation of javalib module even though it can be problematic

**Comment by LeeTibbert** [comment]
Eric, Wojciech,  

Thank you for your time & suggestions on this Issue.

I have deleted `javalib.py`. It has served its purpose and is not
economical to update.

To move the stone forward, how about I create an Issue suggesting that
we would like to start buffing up the javadoc.  Meaning first how to 
generate it, and secondly that it would be good if we could
add javadoc (regular ScalaDoc or some other convention)? to
implementation specific, non-Official_Java_API classes.

Good chores for to pick away at whilst waiting for CI runs
to complete.

Probably means adding a `javalib` badge  to the SN landing
page once we get some cruft cleaned up.

For the next year or so, I think it still worthwhile to provide the
ReadTheDocs javalib list.  That allows anyone who finds the ReadTheDocs
to discover what is implemented instead of having to discover where the
javadoc is published.  Of course, the ReadTheDocs & the new javadoc
should have cross-pointers.

**Comment by armanbilge** [comment]
> Probably means adding a `javalib` badge to the SN landing
> page once we get some cruft cleaned up.

My concern is that this will be confusing. The official Javadoc is also the Javadoc for Scala Native, because we should be implementing it exactly as specified. If we have our own Javadocs, then what is the source-of-truth?

> and secondly that it would be good if we could
add javadoc (regular ScalaDoc or some other convention)? to
implementation specific, non-Official_Java_API classes.

But these are not publicly accessible, which may also generate confusion.

I fully support adding internal, developer-facing documentation to these implementation-specific details. However, we should not publish and promote documentation for these unofficial APIs.

**Comment by LeeTibbert** [comment]
>  However, we should not publish and promote documentation for these unofficial APIs.

I think this advances the discussion.  The Contributor's Guide has fallen to the back of the 
pack and become like an old, creepy, Victorian house.  Perhaps we could not publish
such javadoc as public but in a Contributor's URL, prominently marked as Devo internals?

**Comment by ekrich** [comment]
My only thought is that when an exception message or something was different it could be noted (these are good to document in the code anyway) - `javalib` `scaladoc` would list exactly what is implemented not a replacement for Javadoc - the same goes for `posixlib`, `clib`, and `windowslib`, they are not replacements for official documentation but it doesn't mean it can't have doc comments as needed.

**Comment by LeeTibbert** [comment]
I believe this PR is ready now for merge.  I resolved the prior merge conflict.

**Comment by LeeTibbert** [comment]
@ekrich @WojciechMazur 

Just checking.  Do either of you have a remaining concern with either the concept or implementation
of this PR?

I think it is ready to go, but would like to resolve any lingering final concerns you may have.

Not trying to push the river.

Thank you.

**Comment by WojciechMazur** [comment]
@LeeTibbert Thanks for remainder. I agree it's a good to go. When we'll manage to produce a correct scaladoc then we would be able to replace it, but until that point it's good enoguh

**Comment by LeeTibbert** [comment]
Thank you for the second/third (?) review & merge. I always fear/hate_to pester.

re: " good enough".  I always like to shoot for excellence but sometimes "good enough" is the best we get,
      especially if it is better than what had existed.  I am sure the discussion on javalib scaladoc will continue
      and evolve.

**Pull request merged**
