### PR TITLE
[0.3.x] Add java.util.IdentityHashMap

### PR DESCRIPTION
**Pull request by ekrich**
This is now targeting `0.3.x` first and can be reworked as needed to support `0.4.0`.

### CODE REVIEW

**Comment by ekrich** [comment]
This is PR number 2 to support Native sconfig and thus scalafmt.

**Comment by ekrich** [comment]
@densh Ready for review 😄

**Comment by densh** [comment]
LGTM! Please open against an analogous PR to master as soon as possible.

**Comment by ekrich** [comment]
Refer to Issue #1412

**Pull request merged**
