### PR TITLE
Implement j.net.NetworkInterface & InterfaceAddress classes

### PR DESCRIPTION
**Pull request by LeeTibbert**
The javalib `java.net.NetworkInterface` and `InterfaceAddress` classes allow to enumerate & query the 
network interfaces on a system.

This PR implements these classes on Linux & macOS. A Windows implementation should be possible
but is not part of this PR.

### CODE REVIEW

**Comment by ekrich** [comment]
I noticed you removed the Java 9 test. Note that if you need to add a Java 9 test, there is a special folder that won't get called for Java 8 and mess up CI - https://github.com/scala-native/scala-native/tree/main/unit-tests/shared/src/test/require-jdk9/org/scalanative/testsuite/javalib

**Comment by LeeTibbert** [comment]
Eric,

Thank you for the Java 9 test info URL.  I did not know about that.

If I can get the rest of the huge configuration matrix to pass, I may
loop back and add the Java 9 test.

**Comment by LeeTibbert** [comment]
re: Java 9 tests

Eric, Arman,

The require-9 javalib directory seems to have a `math` directory which is good.
Next sprint, I propose to add a `net` directory and put a new `NetworkInterfaceTestOnJDK9.scala`
in that directory.  

That leaves me wondering why `MathTestOnJDK9.scala` is at the `javalib` level and not
the `javalib.math` level, alongside of the BigInteger test.  Am I missing something subtle
(or obvious)?

Please advise.  Thank you.

**Comment by ekrich** [comment]
I don't see any reason it couldn't be in the math as it is in that package - could have been an oversight but I would be in favor of it being next to the other test and a new `net` dir.

**Comment by armanbilge** [comment]
I think I put that there. The reasoning was because it tests `java.lang.Math`, not `java.lang.math.Math`. But I don't care too much.

**Comment by LeeTibbert** [comment]
> Edit: by that logic maybe it should go in a lang/ directory.

Arman, 
I concur.  If you like, I can do such a PR (tomorrow+) .
(which would also mean changing the package name to javalib.lang)
I also understand if it is easier to knock it off yourself.

I suspect that we will have more files adding JDK9+ features, so
they may well be more `javalib.lang` files.  As the twig is bent....

**Comment by armanbilge** [comment]
Done :)
- https://github.com/scala-native/scala-native/pull/3016

**Comment by LeeTibbert** [comment]
re: Move  

Thank you, that was faster than DoorDash.

**Comment by LeeTibbert** [comment]
The one failing test is our friend `ProcessTest` failing in a way that I have not seen before (a
directory override). I have made a mental note about that failure.    I believe that it has nothing to do with
the content of this PR and may be intermittent (with a long period).

**Comment by LeeTibbert** [comment]
I added the two new classes to  the javalib documentation and remove one which is not part of the
published  Java API.

The doc builds but has an error about libc "time".  That item is fixed in pending PR #3033
and has no relevance, beyond an ugly build, to this PR.

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
