### PR TITLE
Port to JUnit java.lang

### PR DESCRIPTION
**Pull request by ekrich**
There are some small naming updates to `ThreadTest` which was already ported.

Here is a unified diff of the rest. https://gist.github.com/ekrich/bcde340a67bca52d4da90f64d296579a

### CODE REVIEW

**Review by sjrd — APPROVED** [review]

**Comment by ekrich** [comment]
@sjrd Sorry about that, I needed to format a couple of files.

**Review by LeeTibbert — APPROVED** [review]
Eric, thank you for this _huge_ body of work.  LGTM.

I studied the ProcessTest changes in detail, because of some work to be done after the JUnit changes settle.  The intention, as I understand it, was to do a one-for-one transform.  I think you 
were successful at that. The bugs I was chasing, and you had no intent of fixing,
still exist for me to fix and I discovered a new set whilst reviewing.

I did a spot check of other files, and as expected, all was well.  I did notice what I think will
be a _major_ improvement.   Across the board, the Suites used assert(), often times quite a few in one test, with no way to tell which one failed.  I believe that JUnit assertEquals will at least print out the expected and the unexpected values, making it easier to figure out which assertion might be failing.    I believe that asserTrue() does not give us this information for free.

Someday, every assertion will be uniquely identifiable; either by being the only one of its kind in a test, or by having an explicit message argument (even if only "a1", "a2", etc.)

**Comment by ekrich** [comment]
Yes, @sjrd also mentioned about the `assertEquals`. I transformed straight `assert` into the JUnit `assertTrue` so that the JUnit `import` would be not be unused. This also creates work because the comment field is first in JUnit so I had to swap order. Either way, switching to `assertEquals` would not be hard now. 

As we normalize the shared code between Scala Native and Scala.js we can keep the common code at the top and the Scala Native specific/issue tests at the bottom and Scala.js could do the same. I plan to go and work on toggle case test names in Scala.js after this so if we copy tests the names will be more standard. Anyway, it greatly increases the likelihood of sharing.

**Comment by LeeTibbert** [comment]
What I was trying to express is that the necessary one-to-one from assert(e == g) to AssertEquals(e, g) you already did for this PR
gave us some much needed disambiguation for free; that is, for only the labor already spent.  A hidden & bonus bang for the
 buck/CHF for all the time, drive, & effort.

**Pull request merged**
