### PR TITLE
Fix #2780: Drop Scala 2.11

### LINKED ISSUE #2780: Drop Scala 2.11
Since the ecosystem will have to rebuild this is a great time to drop 2.11. This will also help those projects with current 2.11 support since we are not getting new Scala 2.11 releases or security patches anyway. Our CI load burden will go down as well. It is quite large given all the combinations.

### PR DESCRIPTION
**Pull request by ekrich**

### CODE REVIEW

**Comment by ekrich** [comment]
Notes:

1. Had difficulty generating `JProcedure` code so fixed generator `.gyp` and then hand edited. It does not have `// format: off` at the top.
2. `PrepNativeInteropt` has a comment for Scala 2.11 so it looks like I can remove the `DefDef` case but not sure.
3. Both Scala 2 and 3 versions of `NirGenExpr` have comments that I am not sure if they should be changed or not.

**Review by WojciechMazur — APPROVED** [review]
Thank you for your work Eric! I have a few additional changes targeting mostly the handling of implementation classes. I'll try to push these changes soon.

According to your comments: 
* The comments in Scala 2/3 sources related to how anonymous functions/clousers are defined can stay. After all, we're not changing their implementation so it's an important piece of knowledge. 
* One usage from PrepNativeInterop can be removed - I'll handle it in the follow-up commit

There are plenty of potential SAM classes, eg. most of the j.u.f.Consumer, Producer, Function, BiFunction, Predicate. In the future, we might rewrite them to simple lambdas, but it's not a really functional change. For the sake of possible backports from/to Scala.js we probably can leave them in the current boilerplate format.

**Comment by ekrich** [comment]
Thanks @WojciechMazur - I appreciate you being able to finish up.

**Comment by LeeTibbert** [comment]
Most importantly, congratulations on this large & necessary chunk of work.  A day late and a dollar short (i.e. after merge) I noticed that `0.5.0.md` seems not to have been changed.  Certainly this is a breaking change.

**Pull request merged**
