### PR TITLE
Relocate bin/ folder to scripts/ 

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
See #1192

### CODE REVIEW

**Comment by Andrei-Pozolotin** [comment]
possible `bin` location example: `scala-js` is using `scripts`:
* https://github.com/scala-js/scala-js/tree/master/scripts
* https://github.com/scala-js/scala-js/blob/master/.gitignore

**Comment by densh** [comment]
Renaming bin/ to scripts sounds good to me.

**Comment by Andrei-Pozolotin** [comment]
>Renaming bin/ to scripts/ sounds good to me.

make that part of this pr or a new one?

**Comment by densh** [comment]
@Andrei-Pozolotin Lets keep it in the same PR.

**Comment by Andrei-Pozolotin** [comment]
@densh please review

**Comment by Andrei-Pozolotin** [comment]
thank you

**Pull request merged**
