### PR TITLE
Build: Update sbt to 1.9.6

### PR DESCRIPTION
**Pull request by He-Pin**
Build: Update sbt to 1.9.6

### CODE REVIEW

**Comment by ekrich** [comment]
Looks like `setup-java-v3` may not have the Java 21 for Windows yet at least for the distro requested.

**Comment by LeeTibbert** [comment]
https://adoptium.net/temurin/releases/?os=windows is not yet listing JDK 21 as available.

May need to let this PR brew for a week or so.  The JDK 21dependency seems to be buried
in code we do not directly control.
   
I have used sbt 1.9.6 a few (probably less than 10) times in my private work; no smoke.

**Comment by LeeTibbert** [comment]
@he-pin  Thank you for this PR. Please do not get discouraged, nothing is ever simple.

**Comment by He-Pin** [comment]
@ekrich use setup-v4 and zulu.

**Comment by ekrich** [comment]
I don't see a `v4` - https://github.com/actions/setup-java/tags

**Comment by WojciechMazur** [comment]
I've temporally disabled testing with JDK 21, we'll restore it later

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
