### PR TITLE
copying 0 element from an empty array should be a noop

### PR DESCRIPTION
**Pull request by fbertra**
FIX https://github.com/scala-native/scala-native/issues/190

### CODE REVIEW

**Comment by densh** [comment]
Hi @fbertra, please port your tests to the [new unit testing infrastructure](https://github.com/scala-native/scala-native/pull/263).

**Comment by fbertra** [comment]
Hi @densh, I'm back from holidays and will look at this soon.

**Comment by densh** [comment]
Great, thanks!

**Comment by fbertra** [comment]
Too many rebase and merge with git => I'm taking the coward route, closing this PR and filling a new one.

**Pull request closed without merging**
