### PR TITLE
Add partial evaluation

### PR DESCRIPTION
**Pull request by hkapp**
Add partial evaluation as a new pass. It only deals with single instruction patterns.

Because this is a pattern-based pass, there will always be patterns that I didn't think of. Suggestions are welcome !

This is blocked by #466 because it needs `IVal`.

### CODE REVIEW

**Comment by sjrd** [comment]
If you're looking for inspiration: https://github.com/scala-js/scala-js/blob/v0.6.14/tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala#L2722 and https://github.com/scala-js/scala-js/blob/v0.6.14/tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala#L2430

**Comment by hkapp** [comment]
@sjrd thanks, I'll take a look

**Comment by sjrd** [comment]
> Now, how is the handling of shifts done with Longs ? Is it a & 63, similar to the a & 31 for Ints ?

Yes, `& 63` when the left-hand-side is a `Long`.

**Comment by densh** [comment]
#466 has been merged, so this one is not blocked any more.

**Comment by densh** [comment]
LGTM!

**Pull request merged**
