### PR TITLE
Preliminary support for segfault-based safepoints

### PR DESCRIPTION
**Pull request by densh**
Safepoints provide a cheap way to suspend application code and transfer control to the runtime. They are necessary for an upcoming concurrent garbage collector.

### CODE REVIEW

**Comment by DarkDimius** [comment]
While segfault-based safepoints is a good foundation to build performant garbage collection on,
it would make it substantially harder to embed scala-native applications inside virtually anything, in particular to call to scala-native from JNI.

Do you plan to support both modes or is embedding a use-case that is not a priority?

**Comment by densh** [comment]
@DarkDimius Embedding is not supported at the moment, so it's not a concern for now. We can revisit this issue in the future.

**Comment by densh** [comment]
@ekrich `SafepointInsertion` is commented out in the list of passes due to the fact that Boehm GC doesn't need it. It's going to be enabled later in the future PRs.

**Comment by ekrich** [comment]
I thought it was deliberate but wasn't sure, thanks.

**Pull request merged**
