### PR TITLE
Implement java.util.Random

### PR DESCRIPTION
**Pull request by andreaTP**
Ok ready to review :-)

### CODE REVIEW

**Comment by andreaTP** [comment]
ok this could be reviewed!

**Comment by hexsel** [comment]
Would this type of work (implementing java apis) not run into the same type of trouble as Google ran with Android?  https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.

So far, Google is winning, but this is still pending on appeals.

**Comment by andreaTP** [comment]
@hexsel this is a clean room implementation taken from Scala.Js, no way to incriminate this...

**Comment by sjrd** [comment]
Actually, there *is* a way to incriminate this. In theory. Clean room is only the most obvious thing we really have to do not to violate the GPL license. But in theory we could be violating the IP of the APIs.

In practice, Scala.js has been doing this for 3 years and was never so much as called on it. I think we're just not enough of a threat to Oracle nor have enough money to give them that it's worth the effort of suing us ...

**Comment by densh** [comment]
LGTM, thanks @andreaTP ! :cake:

**Pull request merged**
