### PR TITLE
Fix LinkedList.size()

### PR DESCRIPTION
**Pull request by zaneli**

### CODE REVIEW

**Comment by densh** [comment]
Nice catch, @zaneli ! Can you please add a simple unit test to `unit-tests/src/main/scala/java/util` folder to make sure it's fixed for good?

**Comment by zaneli** [comment]
Sure.
I'll add it.

**Comment by zaneli** [comment]
@densh 
I tried to add a test, but it is not works fine. :(
https://travis-ci.org/zaneli/scala-native/jobs/225253216
```
[info] Linking (3681 ms)
[error] cannot link: @java.util.ArrayList
[error] cannot link: @java.util.ArrayList::init_trait.java.util.Collection
[error] cannot link: @java.util.List::add_class.java.lang.Object_bool
[error] cannot link: @java.util.List::clear_unit
[error] cannot link: @java.util.List::isEmpty_bool
[error] cannot link: @java.util.List::iterator_trait.java.util.Iterator
[error] cannot link: @java.util.List::size_i32
[error] unable to link
[error] (tests/*:nativeLinkNIR) unable to link
[error] Total time: 13 s, completed Apr 24, 2017 3:35:09 PM
```

javalib/src/main/scala/java/util/ArrayList.scala seems to be not exist, and [List.scala](https://github.com/zaneli/scala-native/blob/878bb809b3b41e309566f1f57ee729ad64a94dcc/javalib/src/main/scala/java/util/List.scala)'s method is not enough or return type is different.

What should I do on this PR?

**Comment by zaneli** [comment]
> [List.scala](https://github.com/zaneli/scala-native/blob/878bb809b3b41e309566f1f57ee729ad64a94dcc/javalib/src/main/scala/java/util/List.scala)'s method is not enough or return type is different.

Sorry for my lack of understand, [Collection.scala](https://github.com/zaneli/scala-native/blob/878bb809b3b41e309566f1f57ee729ad64a94dcc/javalib/src/main/scala/java/util/Collection.scala) seems to have enough method definition.

But I have no idea for resolve it...

**Comment by zaneli** [comment]
Already fixed by #694 (7e8afe333770f5e5faa97b6ac8ccd8598eecd95b).
I close it.
Thanks.

**Pull request closed without merging**
