### PR TITLE
Rework optimization from #1549

### PR DESCRIPTION
**Pull request by i10416**
This PR reworks parts of #1549
- Seq construction: use List cons + reverse instead of range + map + toSeq
- pattern match order: put frequent ones first

and replaces empty collection's `apply()` with `empty`.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
i10416, 

Thank you  for this PR and improving Scala Native. Reduced time linking would be a good addition.

As a member of the community, rather than as a gatekeeper, I wonder at several things.

As we all know, any discussion or consideration of performance is on shakey ground without
actual measurement.  If only on the order of "I ran this privately. Before a link of SN 0.5.0-SNAPSHOT
took 10 hours; after it took 1 minute".  One can spend eternities & careers considering performance
measurement, but an acknowledge rough first approximation is always useful.

That said, and on a fool's errand because I have no numbers in hand:

1) re: prefer explicit empty to apply()  

    It is probably a good guess to let this change merge.

    This probably saves a few instructions and possibly an object allocation.  I tried
    tracking down the Scala List apply() code but could not find it in the limited
    time & phone screen space I had available.  I would be surprised if it did an
    allocation rather than using a reference to Nil.  List.apply() is near the bottom
    of a stack/tangle of traits, so not obvious to find.

2) put frequent arm first

    The concept is good. jvican's PR is almost 4 years old.  Do we have any idea if
    that priority order is still good?   Because of its age, I did not study it, pardon
   me if I skipped something obvious.   If the data is stale or non-obvious, is there
   any simple way to get current data on a better match order?

**Comment by i10416** [comment]
Thank you for sharing your concern. After re-thinking your feedback, I feel We'd better preparing benchmark suites first. I will close this PR for now.

**Comment by ekrich** [comment]
I think Lee's concerns are valid but we do time the different portions of the compiling and optimizations so if you could see significant improvements then it probably is fine with just a comment like "I always see 5ms improvements on small projects and more on larger ones". It certainly would be good to have benchmarking but that might be a big job.

**Comment by LeeTibbert** [comment]
@i10416   I did not mean to be discouraging, sorry.     

This had seemed like promising, low hanging fruit.

Eric (ekrich) is, as usual, spot on with his "order of magnitude" sizing of effort.

Benchmarking is an entire ~~tar pit~~ discussion.  One could spend lifetimes there
in the span of a single hour. 

There is a Scala Native project with various benchmarks.  I believe it gets manually run
from time to time but may not be current.

At the 10,000 meter level.  Reducing compilation/link time is probably one of the top
two requests for improving Scala Native. I believe, but do not know, that Wojciech
and Densh both have Work In Progress studies/hopes going on to accomplish that.

I have a few spare minutes, let me search the Scala source code again see if  `.empty` saves an allocation.
There is an entire tower of traits.

**Comment by LeeTibbert** [comment]
I spent some time tracing the proposed `.empty` edits of this PR.   I believe that
each edit saves an allocation of a ListBuffer and shortens later code paths by making 
implicit conversion from ListBuffer to List (or Seq) unnecessary.

My recommendation is that this PR be re-opened with only the `.empty` edits
and some small amount of high order performance data be gathered.


Something like "From the relevant CI log files, CI matrix case 3.2.1 took 1 hour in an 
unrelated PR and 20 seconds in this PR".  That avoids spending weeks of time
writing lots of special benchmark code.

I expect the natural variance in CI run times, even
for the no-op change will far outweigh the gain from this PR, but 
at least checking will prevent embarrassing regressions.

Then, given the number of changes to core SN,  ask Wojciech his thoughts
about `.empty` and the other two commits (as future PRs).

**Comment by i10416** [comment]
> My recommendation is that this PR be re-opened with only the .empty edits
and some small amount of high order performance data be gathered.

Something like "From the relevant CI log files, CI matrix case 3.2.1 took 1 hour in an
unrelated PR and 20 seconds in this PR". That avoids spending weeks of time
writing lots of special benchmark code.

Thank you for advice! I'll open another PR focusing on `.empty` stuffs.

**Pull request closed without merging**
