### PR TITLE
Stdbool bindings

### PR DESCRIPTION
**Pull request by sorenbug**
I followed what the `float.h` binding PR did (i.e. I had no real clue what I was doing).

### CODE REVIEW

**Comment by avdv** [comment]
Hi.

According to the ISO C standard, the `true` and `false` identifiers are simply macros, expanding to the integers `1` or `0`, respectively.

Since `CBool` is just an alias for `Boolean` in Scala Native, there's already perfect interop and I see no reason one would use <tt>\`true\`</tt> instead of just `true`...

**Comment by densh** [comment]
@avdv Agreed, I think there is very little reason to use binding to C's stdbool over just `true` and `false` in Scala.

**Comment by sorenbug** [comment]
So then, what about `stdbool` in #104? Does it even make sense in that context?

**Comment by ekrich** [comment]
No I think in that issue and in the documents needs to be removed including any other we know that we don't need. In general, we do the `extern` interfaces to C lib using types that are already included in other interfaces or the ones in https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/unsafe/package.scala . This way we can avoid duplication and nicely tie back to the `Word` and other standard types for our eventual 32 bit support.

**Comment by sorenbug** [comment]
Ok. Thanks for the clarification! :)

**Comment by ekrich** [comment]
There are quite a few moving parts and the beast is evolving as well. Your PR was well meaning so thank-you.

**Comment by densh** [comment]
@sorenbug Sorry for the confusion, that ticket just lists all headers in C library without much thought put in which of those are useful in Scala.

**Comment by sorenbug** [comment]
@densh So then, what will be done about bindgen on libraries that use stdbool?

**Comment by densh** [comment]
stdbool defines:

* `bool` type, it maps to `Boolean` in Scala with 1-to-1 the same semantics and ABI.
* `true` is a macro which doesn't exist on ABI level.
* `false` is a macro which doesn't exist on ABI level.

I believe bindgen already uses `Boolean` for `bool`, so there is nothing to do really.

**Pull request closed without merging**
