### PR TITLE
Add missing commix reference in the documentation

### PR DESCRIPTION
**Pull request by JD557**
Adds a missing "commix" reference to the SBT settings table.

### CODE REVIEW

**Review by ekrich — COMMENTED** [review]
Not sure how that reads exactly but `commix` was added in `0.4.0`.

**Comment by JD557** [comment]
> Not sure how that reads exactly but commix was added in 0.4.0.

The (3) points to the "garbage collection" section, which mentions that:

```
1. **immix.** (default since 0.3.8, introduced in 0.3)
   Immix is a mostly-precise mark-region tracing garbage collector.
   More information about the collector is available as part of the original
   `0.3.0 announcement <https://github.com/scala-native/scala-native/releases/tag/v0.3.0>`_.
2. **commix.** (introduced in 0.4)
   Commix is parallel mark and concurrent sweep garbage collector based on Immix
3. **boehm.** (default through 0.3.7)
   Conservative generational garbage collector. More information is available
   at the Github project "ivmai/bdgc" page.
4. **none.** (experimental, introduced in 0.2)
`

**Review by ekrich — APPROVED** [review]
That makes sense now. LGTM.

**Review by densh — APPROVED** [review]
LGTM! 👍

**Pull request merged**
