### PR TITLE
Remove wrappers around posix API

### PR DESCRIPTION
**Pull request by lolgab**
There was this wrap around posix c api that copied the result in a given buf for safety.
Since our interop is unsafe by definition and we are trying to remove C code as much as possible, this PR removes the `scalanative_` wrapper and links to the original posix functions.

### CODE REVIEW

**Comment by ekrich** [comment]
I agree in principle to this idea, especially removing to nice to have memory management stuff.

Please note that in some cases we need to have differences between the C struct and one to be used by Scala Native thus that weird copying code. I know in `signal.h` or an import to Signal for sure there are structs that are not defined by POSIX so you need to deal with internals for Mac vs Linux. I still haven't finished that one as it is pretty involved.

Also note that in `posix/netinet/in.h`, a header is made so that can be used elsewhere in a C file that needs to use those helpers. Some code may seem like it is not needed or maybe is not even used yet but may be needed in the future.

**Comment by lolgab** [comment]
Thank you @sjrd,
Sure, I'll do!
I have to validate if the concerns @ekrich had hold for this particular case (structs having different structures in different POSIX operative systems).
In case the structs differ in a way we can't have the same representation in different operative systems these can be removed (for what I understand) only if we have link-time conditional compilation.
I'll do my researches and I'll let you know.

**Comment by ekrich** [comment]
Because Scala Native cannot address `struct` fields by name, it reverts to order. POSIX for example only guarantees that the fields exist but says nothing about order or additional fields. These wrappers in C allow the ordered based Scala Native to address the fields directly in the C code. 

I tried to not use wrappers here and it failed. https://github.com/scala-native/scala-native/pull/1751

I recommend we hold off removing until we have proper `struct`s that can address the fields directly.

We also need CI that can build for at least the major platforms Linux and macOS and hopefully Windows at some point.

**Comment by LeeTibbert** [comment]
@lolgab   PR #2093 offers an alternate approach which uses C language features to handle or reject
C struct preconditions.  It does not handle every conceivable Platform, but I think/hope it will 
get well past the Pareto ration (70/30, more likely 95/5).   

That PR handles only time.c.  It has received two positive community
reviews, which I appreciate. Yours  is welcome if you have the time and/or
interest.

Upon approval & merge, the approach could/should be extended to 
other places in posixlib (and clib) where structures are used on
the SN/C boundary.

Someday Scala Native may have direct support for structures.
I have never seen a design for such, but I have heard of the hope 
for such.  The approach of PR #2093 is better than the current
useful but wasteful approach. At the worst it, or an improvement
of it, could be used as a bridge to eventual better support.

**Comment by lolgab** [comment]
Thanks @LeeTibbert,

Closing as superseded by #2093.

**Pull request closed without merging**
