### PR TITLE
WIP: Fix #1753: Build.sbt should report unused imports.

### LINKED ISSUE #1753: Build.sbt scalacOptions should report unused imports
This is a continuation of the concept described in Issue #1748.  The related PR, #1752, removed
a number of warnings, standardized & centralized the handling of scalacOptions, and enabled
-Xfatal-warnings.

Removing the obscuring shrubbery of warnings allows leveling up and using the compiler
to detect poor software engineering practices.

@ekrich  suggested adding `-Ywarn-unused-import` and I concur.  This allows the removal
of useless distractions when tracing code.

I did not include this option in PR #1748 because when I tried it I got 20-something detections in 
the first sub-project (nir) alone. Most of those were in separate files.   That would mean high
tens of files in the entire SN build.

I punted the change to this Issue and its  corresponding PR o keep the number of files changed in PR #1748 to a count where reviewers can concentrate on the key issue, warnings, of that PR.

Other scalacOptions are available and can be candidates of additional Issues.

The challenge is to find a proper ratio of investment of time in nano-issues when SN has Macro-scala issues.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* Because of the 153 files changed, the prospect of review looks scary at first sight.
    The relevant changes are a few lines in build.sbt.  After that, it is removing
    unused imports in 152 files.  The all green build gives confidence that nothing unintended
    was deleted/dinged in the removal process. 

  * This PR was motivated by Issue #1753 "Build.sbt scalacOptions should
    report unused imports".

    That Issue is now fixed.  The scalac 2.11 option "-Ywarn-unused-import"
    is now used in all sub-projects except scalalib and sandbox.

    scalalib contains the original sources to scala itself. It does not
    make sense to edit these originals. Also there are over 200+
    unused imports.

    The sandbox project tends to get used in the scala REPL and for
    debugging. The presence of "-Ywarn-unused-import" tends to
    make those activities more difficult.

    "-Ywarn-unused-import" changes for scala 2.12 and then again for
    2.13. A few "heads up" comments were left for future maintainers.

  * How do I know which imports are unused? The compiler told me so.
    Now I just have to hope that there is not some underlying
    build wizardry that I missed.

  * I lost count in the middle but there were at least 250 or so
    unused imports, probably closer to 300 or 350.

    Future developers can spend less time chasing code which is
    never used.

  * Because of the large number of changes to nearly every part of the
    build, the earlier this PR can be accepted, the better. It will
    get more exercise and there will be fewer merge conflicts.
    It is pretty much a "use it or loose it!" endeavour.
    
Documentation:

  * The affected files are all internal to the Scala Native build itself.
    Any change visible to a developer using Scala Native artifacts
    is unintentional and a bug.

Testing:

  * Built ("rebuild")and tested ("test-all") in debug mode using sbt 1.3.7
    & Java 8 on X86_64 only . All tests pass. grep "\[warn\]" of the logfile
    reports zero occurrences.

  * Built and tested ("test-all") in release-fast mode using
    sbt 1.3.7 & Java 8 on X86_64 only . All tests pass.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Moved to Work in Progress (WIP) until after PR #1752 is merged.  Edits to code in flux are too
complicated for time available.

Concept is good, & works and should be implemented in the near future.

**Comment by hepin1989** [comment]
Do it with `scalafix RemoveUnused` is better for future maintenance.

**Comment by LeeTibbert** [comment]
@hepin1989 Thank you for the scalafix suggestion.  I think I now understand what you mean.
Because scalafix requires that -Xfatal-warnings be disabled, I think that adding the scalafix
to the mainline repo is not worth the loss.   

I can see if the Zio folks have figured out a way to have both.

I do see, now, how the next time I have to futz with this I could save myself a _huge_ amount of time
and reduce the chances that I introduced unwanted errors by using scalafix in my private developement repo.

I hope someday to do a run removing unused variables, etc and will keep your suggestion in mind.

**Comment by ekrich** [comment]
I think the title of the PR has sufficient scope. If we have a way to identify the unused imports and they are cleaned up then we have reduced the technical debt and put in place a process that will help us keep the code base clean. That is a big win.

**Comment by hepin1989** [comment]
I think we can add a new plugin to update the proper setup if we want to fix something via explicit invocation.

**Comment by LeeTibbert** [comment]
@hepin1989  I was slow on the uptake but now that I think I understand your suggestion, I am
doing a private engineering design study to explore the possibility of adding the scalafix plugin,
for optional and manual invocation.

Unfortunately, it is not as simple as adding a few lines of code from the scalafix installation page.
Promising and good to know about, but not drop in.   The SN code base is established, relatively
large, and tricky. 
More later, as I understand more.

**Comment by LeeTibbert** [comment]
Progress note.   The CI build of this PR is broken because the PR is doing its job.  Some
files with unused imports entered mainline after this PR was created and this PR complains
about those unused imports.

The obvious rebase did not work. I am studying the possibilities of scalafix. I think I will
be falling back to a third option in an attempt to rescue this PR.

More as it develops.

**Comment by ekrich** [comment]
@LeeTibbert I think that perhaps that adding rewrite rules to the `scalafmt` might be an option but the more complex the configuration gets, the harder it is to maintain.

I do think I prefer that idea vs adding the `sbt-scalafix` plugin which adds even more magic and cognitive load. I prefer the minimum set of tools to do the job. https://scalacenter.github.io/scalafix/docs/users/installation

**Comment by LeeTibbert** [comment]
After a __long__ day of studying scalafix, it looks like an excellent solution, but one that
must remain out-of-band.  That is, not part of the regular build (because of overhead and exposing
complexity for a seldom used feature.) but part of wizardry, if you can find the right wizard,
manually execuated once in a blue moon.  Not a great solution, but appropriate to a 
small project.  

Using a reasonably proven/exercised machine tool to make one set of defined changes over hundreds of files increases the confidence that only the intended changes were made. Agreed, it
 does lack independent reproducibility.   I think it is a situation better than what it wants to 
replace.

**Comment by LeeTibbert** [comment]
Once again, I am moving this back to WIP.  The concept is right and the build.sbt is right but
files with unused-imports crept in over the month or so and the merge is too difficult for me to do
and too difficult to convince reviewers that it is correct.

Based on some scalafix studies I have been doing, I will re-do a PR .  It will not add scalafix to
the SN build, but will add some automation to the elimination of unused imports.

**Comment by LeeTibbert** [comment]
The good news is that the PR queue is active.  Time for me to back off  this work until a more
appropriate time.  That will clear the decks for current work.

I did learn how to use scalafix, so the WIP was beneficial.

**Pull request closed without merging**
