### PR TITLE
Align error messages for `UnknownHost` with JVM

### PR DESCRIPTION
**Pull request by armanbilge**
Targeting 0.4.x

### CODE REVIEW

**Comment by LeeTibbert** [comment]
A small mercy, thank you.

**Review by ekrich — APPROVED** [review]
Thank you for this PR and the shared tests.
LGTM.

**Comment by LeeTibbert** [comment]
I manually merged this code into the 0.5.0 PR #2803. I hope this makes merging 0.4.x into 0.5.0.

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
@arman  For my sins I am deeply into `InetAddressTest.scala`.  I thought I would share my ~~misery~~ pain.

Under the rubric of "no good deed goes unpunished", I thought I would consult with you before I make some
edits which would undo your careful work. 

I merged your work (thank you) into the 0.5.n stream.  The code I am looking directly at is:
```
    assertThrows(
      "not.example.com: Name or service not known",
      classOf[UnknownHostException],
      InetAddress.getByName("not.example.com")
    )
```

You mentioned aligning the text with the JVM.  Do you remember
which JVM you used?  

Scastie (Scala JVM on the web) and macOS both give different messages
(which also differ from the text from before your PR).  

Now, this test passes on both linux, and macOS.  I think the reason that 
it does is that `assertThrows` on Scala Native (and perhaps JUnit in general)
takes that first string line as a message to throw when the assertion fails,
rather than something to be checked against the message text in the Exception.

There are at least two variants of `assertThrows` in the SN codebase.  I checked
both but may have missed others.

I have seen some test harnesses which _do_ test for the exact text.
I actually thought that SN worked that way until I traced code.

Am I missing or misinterpreting something or have I fallen totally
off the track.

I think the fix is to delete the "match-this" text, probably in several places.
I am about to submit a 0.5.0 PR for  `InetAddressTest.scala` and can 
make the changes there.  I can do the deletions in the 0.4.n stream
if you think it worthwhile.  

You always have a pretty good reason for doing things, so I will make
no changes until you advise.

Thank you for your time.

**Comment by armanbilge** [comment]
@LeeTibbert thanks for bringing this to my attention. Indeed, my intention was to test for the precise message in the exception, and you are right that the assertion does not actually do that. Rats :)

When I made this change, I was working on https://github.com/Comcast/ip4s/pull/424 with the goal to get this test to pass on JVM, Node.js, and Native:

https://github.com/Comcast/ip4s/blob/043159fd6e3a5af596f9485688e79c0176a51578/test-kit/shared/src/test/scala/com/comcast/ip4s/DnsTest.scala#L49-L53

It looks like CI for that project is using `Temurin Java 1.8.0_345`. As we know, messages (and grammar) tend to vary between JDKs and OSes. So perhaps we will have to special-case this one.

What are the error messages that you are observing?

**Comment by LeeTibbert** [comment]
I think the fix is to change what looks like is trying to match the exact Exception message
`   "not.example.com: Name or service not known",`
to something  which identifies the failing test, like:
`getByName("not.example.com")`

That is, make it clear that one is not attempting to match the exact text.

**Comment by LeeTibbert** [comment]
>      .interceptMessage[UnknownHostException]("not.example.com: Name or service not known")
The original URL is helpful.

Does that test pass on macOS using say Zulu?

**Comment by LeeTibbert** [comment]
> .interceptMessage[UnknownHostException]("not.example.com: Name or service not known")

Since you do not control the JVM, seems like the best you can do is to test for `[UnknownHostException]`
and not the exact text.  I can see where you want the exact-text message in code you control.

Does `interceptMessage` have a ` .interceptMessage[UnknownHostException]` form?

**Comment by armanbilge** [comment]
The reason I became more strict about matching messages across platforms was because downstream libraries depend on them in certain situations. For example see https://github.com/http4s/http4s/pull/5290#discussion_r719041517 regarding this code:

https://github.com/http4s/http4s/blob/f3e23f30c2c950eb377c5eec94a21301280a0ad3/ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala#L262-L270

Although I think that in this case matching messages exactly is probably not so important.

**Comment by LeeTibbert** [comment]
>  msg == "Connection reset by peer" || msg == "Broken pipe"
Do you have any guarantee that you are in the C locale? If yes, those
are probably the best you can do if the locale independent errno has
been lost by then.  

Circling back home:  If you concur, I will change the text in 0.5.0 to make
it clear which test is failing (and that it is not trying to match the underlying 
`ex.getMessage()`.   I will also place a comment in `InetAddress.scala`
in the place where the Exception is thrown describing where the
exact text came from (temurin above), that it differs on scastie
and macOS, and that changing it will break some/many
version of `ex.getMessage()`.  

How does that sound as a way to tie this up?

**Comment by armanbilge** [comment]
👍 sounds good to me, thank you for your work and investigation on this!

**Comment by LeeTibbert** [comment]
and I appreciate the helpful consult.

**Pull request merged**
