### PR TITLE
Support mingw compiler

### LINKED ISSUE #3862: Exception handling Windows / Unix with llvm-mingw / zig cc
Hi.

I am still trying to cross-compile my project on Linux to Windows x86_64 using zig cc.

I have set the target triple to `x86_64-unknown-windows-gnu`.

The issue I am running into is that scala-native emits `__CxxFrameHandler3` and `type_info::vftable`:
```
LLD Link... lld-link: error: undefined symbol: __CxxFrameHandler3
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/5b42b00c.ll.o:(.xdata)
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/5b42b00c.ll.o:(.xdata)
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/5b42b00c.ll.o:(.xdata)
>>> referenced 2752 more times

lld-link: error: undefined symbol: const type_info::`vftable'
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/5b42b00c.ll.o:(class scalanative::ExceptionWrapper `RTTI Type Descriptor')
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/dd42d030.ll.o
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/71cea4cd.ll.o
```
AFAIU, these symbols are specific to Microsoft's compiler (or rather Microsoft's C++ runtime support library).

I have changed scala-native (via Byteman) to use `UnixCompat` instead of `WindowsCompat` codegen for my project.

This solves the first problem but results in a different undefined symbol:
```
LLD Link... lld-link: error: undefined symbol: __gxx_personality_v0
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/5b42b00c.ll.o:(.xdata)
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/5b42b00c.ll.o:(GCC_except_table209)
>>> referenced by /home/claudio/code/native/target/scala-3.3.3/native/generated/dd42d030.ll.o:(.xdata)
```
According to [this](https://github.com/msys2/MINGW-packages/issues/368) issue the mentioned symbol should be used on win32 (i686), but on x86_64 `__gxx_personality_seh0` is used instead.

I have verified this using mingw-llvm:
```console
# i686
$ /opt/llvm-mingw/llvm-mingw-20240320-ucrt-ubuntu-20.04-x86_64/bin/i686-w64-mingw32-g++ div.cpp -c -o div_i686.o
$ /opt/llvm-mingw/llvm-mingw-20240320-ucrt-ubuntu-20.04-x86_64/bin/i686-w64-mingw32-nm div_i686.o | grep personal
         U ___gxx_personality_v0
# x86_64
$ /opt/llvm-mingw/llvm-mingw-20240320-ucrt-ubuntu-20.04-x86_64/bin/x86_64-w64-mingw32-c++ -c div.cpp -o div_x86-64.o
$ /opt/llvm-mingw/llvm-mingw-20240320-ucrt-ubuntu-20.04-x86_64/bin/x86_64-w64-mingw32-nm div_x86-64.o | grep personal
         U __gxx_personality_seh0
```

Is this analysis correct? What could be a way forward here? Thanks!

### PR DESCRIPTION
**Pull request by avdv**
This PR includes the minimal changes to make it possible to use mingw (e.g. llvm-mingw or zig cc). Fixes #3862 

As mentioned in #3862, mingw on Windows x86_64 uses the Itanium ABI with SEH.

I tried to use llvm-mingw with the more modern ucrt, but ran into compilation errors. So I switched to llvm-mingw with msvcrt for my testing. I ran CI in my fork with llvm-mingw 16.0.6 and 17.0.6. (see https://github.com/avdv/scala-native/actions/runs/8641795183)

Currently, there are two tests that still fail:

1. org.scalanative.testsuite.javalib.lang.DoubleTest
2. org.scalanative.testsuite.javalib.net.SocketTest (apparently only fails in "Test runtime (3, boehm)" but no other workflow)

and these scripted tests fail:

1. run/backtrace
2. run/build-library-dynamic
3. run/build-library-static

Note, in order for llvm-mingw to generate pdb's (and make stack traces work), one has to pass `-gcodeview` and `-Wl,--pdb=` as linking options.

How should this be integrated with CI? I assume a new workflow could be added that is using llvm-mingw. WDYT?

### CODE REVIEW

**Review by WojciechMazur — APPROVED** [review]

**Comment by philwalk** [comment]
Hi all, I'm very interested in using the MINGW compiler, and was able to get some code to compile a couple of years ago, but haven't experimented with it since then.
Is there documentation for how to configure things?   There are quite a few variations and experimenting is time-expensive.

**Comment by avdv** [comment]
> Hi all, I'm very interested in using the MINGW compiler, and was able to get some code to compile a couple of years ago, but haven't experimented with it since then. Is there documentation for how to configure things? There are quite a few variations and experimenting is time-expensive.

You can have a look at this branch: https://github.com/scala-native/scala-native/compare/main...avdv:scala-native:refs/heads/windows-gnu-compiler

It has a working CI setup using llvm-mingw instead of the default llvm toolchain. See https://github.com/scala-native/scala-native/commit/754d39733ae6b52d6719b06b1b7948bf373bcdeb, https://github.com/scala-native/scala-native/commit/9defdcdad33325d8d46b8f6c86f3e77ad5868f4b and https://github.com/scala-native/scala-native/commit/1130d34d302a2ec7e355028e7110b9794c9c7b3d

HTH

**Comment by philwalk** [comment]
> You can have a look at this branch: [main...avdv:scala-native:refs/heads/windows-gnu-compiler](https://github.com/scala-native/scala-native/compare/main...avdv:scala-native:refs/heads/windows-gnu-compiler)

Hi, thanks for the info!   When I click on the link, a page comes up offering the opportunity to create a PR, not what I want to do.   

Is there a way to clone a branch that combines all of these commits?

image

**Comment by avdv** [comment]
> > You can have a look at this branch: [main...avdv:scala-native:refs/heads/windows-gnu-compiler](https://github.com/scala-native/scala-native/compare/main...avdv:scala-native:refs/heads/windows-gnu-compiler)
> 
> Hi, thanks for the info! When I click on the link, a page comes up offering the opportunity to create a PR, not what I want to do.

Just ignore the button then.
 
> Is there a way to clone a branch that combines all of these commits?

You don't need all of these commits, because most of them are already incorporated into scala-native (https://github.com/scala-native/scala-native/pull/3855 and this PR).
 
Basically, you only need to install llvm-mingw (msvcrt variant) and use it with your scala-native project. I am not using Windows so I don't know much more about the details and can only suggest to look at how CI is set up and replicate that on your machine.

**Comment by ekrich** [comment]
I took a look at the code and there is support for the `...windows.msys` target triple along with some special options. @philwalk, if you get it going then perhaps you could add the setup to getting started docs for this setup.

**Pull request merged**
